/**
 * The eight professional slide themes. Each `buildSlides` returns a demo deck of
 * six slides (cover, section, content, two-column, stat, closing) that exercise
 * the theme's palette, fonts, and signature decorative shapes.
 */

import {
  type ThemeSpec,
  type Box,
  glassPanel,
  image,
  kicker,
  linearFill,
  shape,
  slide,
  text,
} from "./theme-kit";

const bullets = (items: string[]) =>
  items.map((t) => ({ text: t, listType: "bullet" as const }));

/* ======================================================================= *
 * 1. CLARITY — clean business layouts
 * ======================================================================= */

const clarity: ThemeSpec = {
  id: "clarity",
  name: "Clarity",
  tagline: "Clean business layouts that keep the content in front.",
  palette: {
    slideBg: "#ffffff",
    surface: "#f1f5f9",
    accent: "#2563eb",
    onBg: "#0f172a",
    onSurface: "#1e293b",
    onAccent: "#ffffff",
    muted: "#64748b",
    deco: ["#2563eb", "#dbeafe", "#94a3b8"],
  },
  fonts: {
    heading: "inter",
    body: "source-sans-3",
    headingCss: "'Inter', 'Noto Sans SC', system-ui, sans-serif",
    bodyCss: "'Source Sans 3', 'Noto Sans SC', system-ui, sans-serif",
  },
  cornerRadiusPt: 4,
  shadowCss: "none",
  defaultBackground: { type: "solid", color: "#ffffff" },
  masterBackground: { type: "solid", color: "#ffffff" },
  buildSlides: (spec) => {
    const palette = spec.palette;
    const fonts = spec.fonts;
    const rule = (zIndex: number, box: Box, color = palette.accent) =>
      shape({
        zIndex,
        shape: "rect",
        box,
        fill: color,
        locked: true,
        name: "Rule",
      });
    return [
      slide("clarity-cover", "Clarity", "title", [
        rule(1, { x: 8, y: 29, w: 13, h: 0.7 }),
        shape({
          zIndex: 1,
          shape: "rect",
          box: { x: 69, y: 0, w: 31, h: 100 },
          fill: palette.surface,
          locked: true,
          name: "Side panel",
        }),
        shape({
          zIndex: 2,
          shape: "rect",
          box: { x: 73, y: 18, w: 18, h: 0.5 },
          fill: palette.deco[2],
          locked: true,
          name: "Panel rule",
        }),
        kicker(
          9,
          { x: 8, y: 22, w: 48, h: 5 },
          "BOARD BRIEF · 2026",
          palette.accent,
          fonts.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 7.5, y: 34, w: 58, h: 24 },
          role: "title",
          text: "Make the case\nclearly",
          style: {
            fontSize: 8.4,
            color: palette.onBg,
            fontId: fonts.heading,
            bold: true,
            align: "left",
            lineHeight: 1.02,
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 63, w: 52, h: 10 },
          role: "subtitle",
          text: "A structured package for decisions, plans, and operating updates.",
          style: {
            fontSize: 3.3,
            color: palette.muted,
            fontId: fonts.body,
            align: "left",
            lineHeight: 1.35,
          },
        }),
      ]),
      slide(
        "clarity-section",
        "Section",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: palette.accent,
            locked: true,
            name: "Field",
          }),
          text({
            zIndex: 9,
            box: { x: 8, y: 28, w: 24, h: 8 },
            text: "01",
            style: {
              fontSize: 5,
              color: "#bfdbfe",
              fontId: fonts.heading,
              bold: true,
              align: "left",
            },
          }),
          rule(9, { x: 8, y: 39, w: 10, h: 0.7 }, "#bfdbfe"),
          text({
            zIndex: 10,
            box: { x: 8, y: 45, w: 72, h: 18 },
            role: "sectionTitle",
            text: "What matters now",
            style: {
              fontSize: 7,
              color: "#ffffff",
              fontId: fonts.heading,
              bold: true,
              align: "left",
            },
          }),
        ],
        { type: "solid", color: palette.accent },
      ),
      slide("clarity-content", "Update", "content", [
        text({
          zIndex: 10,
          box: { x: 7, y: 10, w: 72, h: 8 },
          role: "title",
          text: "Current operating picture",
          style: {
            fontSize: 5.3,
            color: palette.onBg,
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        rule(9, { x: 7, y: 20, w: 86, h: 0.35 }, palette.deco[2]),
        text({
          zIndex: 11,
          box: { x: 8, y: 28, w: 43, h: 48 },
          role: "bullet",
          paragraphs: bullets([
            "Demand remains healthy across priority accounts.",
            "Execution risk is concentrated in launch sequencing.",
            "The next decision should lock scope and owner model.",
          ]),
          style: {
            fontSize: 3.2,
            color: palette.onSurface,
            fontId: fonts.body,
            lineHeight: 1.55,
            paragraphSpacing: 1.7,
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 57, y: 27, w: 35, h: 48 },
          fill: palette.surface,
          radius: 6,
          locked: true,
          name: "Summary panel",
        }),
        text({
          zIndex: 10,
          box: { x: 60, y: 32, w: 29, h: 6 },
          role: "label",
          text: "DECISION",
          style: {
            fontSize: 2.5,
            color: palette.accent,
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 60, y: 40, w: 29, h: 26 },
          role: "body",
          text: "Commit to the focused release path and move exploratory items to the next planning cycle.",
          style: {
            fontSize: 3.1,
            color: palette.onBg,
            fontId: fonts.body,
            lineHeight: 1.45,
            align: "left",
          },
        }),
      ]),
      slide("clarity-twocol", "Options", "two-column", [
        text({
          zIndex: 10,
          box: { x: 7, y: 10, w: 72, h: 8 },
          role: "title",
          text: "Two options, one recommendation",
          style: {
            fontSize: 5.3,
            color: palette.onBg,
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        rule(9, { x: 7, y: 20, w: 86, h: 0.35 }, palette.deco[2]),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 7, y: 27, w: 40, h: 52 },
          fill: palette.surface,
          radius: 6,
          locked: true,
          name: "Left card",
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 53, y: 27, w: 40, h: 52 },
          fill: "#ffffff",
          stroke: { color: palette.accent, width: 0.5 },
          radius: 6,
          locked: true,
          name: "Right card",
        }),
        text({
          zIndex: 10,
          box: { x: 10, y: 32, w: 34, h: 6 },
          role: "label",
          text: "OPTION A",
          style: {
            fontSize: 2.6,
            color: palette.muted,
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 10, y: 39, w: 34, h: 34 },
          role: "bullet",
          paragraphs: bullets([
            "Lower disruption",
            "Faster approval",
            "Limited upside",
          ]),
          style: {
            fontSize: 3.1,
            color: palette.onSurface,
            fontId: fonts.body,
            lineHeight: 1.55,
            paragraphSpacing: 1.5,
          },
        }),
        text({
          zIndex: 10,
          box: { x: 56, y: 32, w: 34, h: 6 },
          role: "label",
          text: "OPTION B",
          style: {
            fontSize: 2.6,
            color: palette.accent,
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 56, y: 39, w: 34, h: 34 },
          role: "bullet",
          paragraphs: bullets([
            "Higher upside",
            "Clearer ownership",
            "Requires sequencing",
          ]),
          style: {
            fontSize: 3.1,
            color: palette.onSurface,
            fontId: fonts.body,
            lineHeight: 1.55,
            paragraphSpacing: 1.5,
          },
        }),
      ]),
      slide("clarity-stat", "Metric", "title", [
        kicker(
          9,
          { x: 8, y: 24, w: 44, h: 5 },
          "HEADLINE SIGNAL",
          palette.accent,
          fonts.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 7.5, y: 31, w: 58, h: 26 },
          text: "86%",
          style: {
            fontSize: 17,
            color: palette.accent,
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 61, w: 62, h: 10 },
          role: "subtitle",
          text: "of priority work is now tied to named accountable owners.",
          style: {
            fontSize: 3.5,
            color: palette.onSurface,
            fontId: fonts.body,
            align: "left",
            lineHeight: 1.35,
          },
        }),
        shape({
          zIndex: 1,
          shape: "rect",
          box: { x: 72, y: 18, w: 16, h: 60 },
          fill: palette.surface,
          radius: 8,
          locked: true,
          name: "Metric bar",
        }),
        shape({
          zIndex: 2,
          shape: "rect",
          box: { x: 72, y: 40, w: 16, h: 38 },
          fill: palette.accent,
          radius: 8,
          locked: true,
          name: "Metric fill",
        }),
      ]),
      slide("clarity-closing", "Next steps", "title", [
        shape({
          zIndex: 1,
          shape: "rect",
          box: { x: 0, y: 0, w: 100, h: 100 },
          fill: palette.onBg,
          locked: true,
          name: "Field",
        }),
        rule(2, { x: 8, y: 43, w: 12, h: 0.7 }, palette.accent),
        text({
          zIndex: 10,
          box: { x: 8, y: 48, w: 68, h: 13 },
          role: "title",
          text: "Clear next steps.",
          style: {
            fontSize: 8,
            color: "#ffffff",
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 64, w: 60, h: 8 },
          role: "subtitle",
          text: "Confirm scope, assign owners, review in two weeks.",
          style: {
            fontSize: 3.2,
            color: "#cbd5e1",
            fontId: fonts.body,
            align: "left",
          },
        }),
      ]),
    ];
  },
};

/* ======================================================================= *
 * 2. OCEAN — clear product and data layouts
 * ======================================================================= */

const ocean: ThemeSpec = {
  id: "ocean",
  name: "Ocean",
  tagline: "Clear product and data layouts with blue-green depth.",
  palette: {
    slideBg: "#f6fbff",
    surface: "#e0f2fe",
    accent: "#0284c7",
    onBg: "#0c4a6e",
    onSurface: "#075985",
    onAccent: "#ffffff",
    muted: "#0e7490",
    deco: ["#38bdf8", "#99f6e4", "#bae6fd"],
  },
  fonts: {
    heading: "space-grotesk",
    body: "inter",
    headingCss: "'Space Grotesk', 'Noto Sans SC', system-ui, sans-serif",
    bodyCss: "'Inter', 'Noto Sans SC', system-ui, sans-serif",
  },
  cornerRadiusPt: 8,
  shadowCss: "0 14px 32px rgba(2,132,199,0.14)",
  defaultBackground: { type: "solid", color: "#f6fbff" },
  masterBackground: { type: "solid", color: "#f6fbff" },
  buildSlides: (spec) => {
    const palette = spec.palette;
    const fonts = spec.fonts;
    const current = (zIndex: number, box: Box, color: string, opacity = 0.3) =>
      shape({
        zIndex,
        shape: "ellipse",
        box,
        fill: color,
        effect: { kind: "blur", radius: 8 },
        opacity,
        locked: true,
        name: "Current",
      });
    return [
      slide("ocean-cover", "Ocean", "title", [
        current(1, { x: 60, y: -22, w: 62, h: 76 }, palette.deco[0], 0.25),
        current(2, { x: 70, y: 20, w: 44, h: 58 }, palette.deco[1], 0.35),
        kicker(
          9,
          { x: 8, y: 27, w: 48, h: 5 },
          "PRODUCT REVIEW · 2026",
          palette.accent,
          fonts.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 7.5, y: 34, w: 66, h: 25 },
          role: "title",
          text: "Navigate with\nbetter signals",
          style: {
            fontSize: 8.8,
            color: palette.onBg,
            fontId: fonts.heading,
            bold: true,
            align: "left",
            lineHeight: 1.02,
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 64, w: 56, h: 10 },
          role: "subtitle",
          text: "A calm operating view for product, customer, and market data.",
          style: {
            fontSize: 3.4,
            color: palette.muted,
            fontId: fonts.body,
            align: "left",
            lineHeight: 1.35,
          },
        }),
      ]),
      slide(
        "ocean-section",
        "Depth",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: palette.onBg,
            locked: true,
            name: "Field",
          }),
          current(2, { x: -16, y: 48, w: 58, h: 72 }, palette.deco[0], 0.16),
          current(3, { x: 70, y: -20, w: 52, h: 70 }, palette.deco[1], 0.18),
          text({
            zIndex: 10,
            box: { x: 8, y: 30, w: 30, h: 8 },
            text: "02",
            style: {
              fontSize: 5.4,
              color: palette.deco[1],
              fontId: fonts.heading,
              bold: true,
              align: "left",
            },
          }),
          text({
            zIndex: 11,
            box: { x: 8, y: 43, w: 76, h: 20 },
            role: "sectionTitle",
            text: "Signals below\nthe surface",
            style: {
              fontSize: 8,
              color: "#ffffff",
              fontId: fonts.heading,
              bold: true,
              align: "left",
              lineHeight: 1.02,
            },
          }),
        ],
        { type: "solid", color: palette.onBg },
      ),
      slide("ocean-content", "Signals", "content", [
        current(1, { x: 76, y: 72, w: 30, h: 40 }, palette.deco[0], 0.16),
        kicker(
          9,
          { x: 8, y: 12, w: 42, h: 5 },
          "SIGNALS",
          palette.accent,
          fonts.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 8, y: 18, w: 58, h: 12 },
          role: "title",
          text: "What changed this quarter",
          style: {
            fontSize: 5.5,
            color: palette.onBg,
            fontId: fonts.heading,
            bold: true,
            align: "left",
            lineHeight: 1.06,
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 34, w: 43, h: 48 },
          role: "bullet",
          paragraphs: bullets([
            "Activation recovered after onboarding simplification.",
            "Enterprise cycles are longer but higher confidence.",
            "Retention lift is strongest where support touch is early.",
          ]),
          style: {
            fontSize: 3.2,
            color: palette.onSurface,
            fontId: fonts.body,
            lineHeight: 1.55,
            paragraphSpacing: 1.7,
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 57, y: 30, w: 35, h: 46 },
          fill: palette.surface,
          radius: 12,
          locked: true,
          name: "Metric card",
        }),
        text({
          zIndex: 10,
          box: { x: 60, y: 35, w: 28, h: 9 },
          text: "+18%",
          style: {
            fontSize: 6.4,
            color: palette.accent,
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 60, y: 48, w: 28, h: 16 },
          role: "caption",
          text: "qualified activation after the product education update.",
          style: {
            fontSize: 2.8,
            color: palette.onSurface,
            fontId: fonts.body,
            lineHeight: 1.35,
            align: "left",
          },
        }),
      ]),
      slide("ocean-twocol", "Compare", "two-column", [
        text({
          zIndex: 10,
          box: { x: 8, y: 12, w: 76, h: 8 },
          role: "title",
          text: "Current versus target state",
          style: {
            fontSize: 5.4,
            color: palette.onBg,
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 8, y: 28, w: 40, h: 54 },
          fill: "#ffffff",
          stroke: { color: palette.deco[2], width: 0.5 },
          radius: 12,
          locked: true,
          name: "Left card",
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 52, y: 28, w: 40, h: 54 },
          fill: palette.surface,
          radius: 12,
          locked: true,
          name: "Right card",
        }),
        text({
          zIndex: 10,
          box: { x: 11, y: 33, w: 34, h: 6 },
          role: "label",
          text: "CURRENT",
          style: {
            fontSize: 2.6,
            color: palette.muted,
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 11, y: 40, w: 34, h: 36 },
          role: "bullet",
          paragraphs: bullets([
            "Signal spread across tools",
            "Weekly readouts",
            "Reactive account motion",
          ]),
          style: {
            fontSize: 3.05,
            color: palette.onSurface,
            fontId: fonts.body,
            lineHeight: 1.55,
            paragraphSpacing: 1.45,
          },
        }),
        text({
          zIndex: 10,
          box: { x: 55, y: 33, w: 34, h: 6 },
          role: "label",
          text: "TARGET",
          style: {
            fontSize: 2.6,
            color: palette.accent,
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 55, y: 40, w: 34, h: 36 },
          role: "bullet",
          paragraphs: bullets([
            "One decision surface",
            "Daily signal quality",
            "Proactive customer plays",
          ]),
          style: {
            fontSize: 3.05,
            color: palette.onSurface,
            fontId: fonts.body,
            lineHeight: 1.55,
            paragraphSpacing: 1.45,
          },
        }),
      ]),
      slide("ocean-stat", "Lift", "title", [
        current(1, { x: 60, y: 20, w: 54, h: 74 }, palette.deco[0], 0.16),
        kicker(
          9,
          { x: 8, y: 24, w: 44, h: 5 },
          "RETENTION LIFT",
          palette.accent,
          fonts.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 7.5, y: 31, w: 60, h: 26 },
          text: "+11 pts",
          style: {
            fontSize: 15,
            color: palette.accent,
            fontId: fonts.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 61, w: 62, h: 10 },
          role: "subtitle",
          text: "net retention improvement in teams using the new health model.",
          style: {
            fontSize: 3.5,
            color: palette.onSurface,
            fontId: fonts.body,
            align: "left",
            lineHeight: 1.35,
          },
        }),
      ]),
      slide(
        "ocean-closing",
        "Course",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: palette.onBg,
            locked: true,
            name: "Field",
          }),
          current(2, { x: 58, y: 18, w: 58, h: 80 }, palette.deco[0], 0.18),
          text({
            zIndex: 10,
            box: { x: 8, y: 40, w: 68, h: 14 },
            role: "title",
            text: "Stay on course.",
            style: {
              fontSize: 8,
              color: "#ffffff",
              fontId: fonts.heading,
              bold: true,
              align: "left",
            },
          }),
          text({
            zIndex: 11,
            box: { x: 8, y: 58, w: 60, h: 8 },
            role: "subtitle",
            text: "Focus the next sprint on signal quality and account motion.",
            style: {
              fontSize: 3.2,
              color: "#bae6fd",
              fontId: fonts.body,
              align: "left",
            },
          }),
        ],
        { type: "solid", color: palette.onBg },
      ),
    ];
  },
};

/* ======================================================================= *
 * 3. AURORA — modern tech / SaaS keynote
 * ======================================================================= */

const aurora: ThemeSpec = {
  id: "aurora",
  name: "Aurora",
  tagline: "Modern tech & SaaS keynote — luminous gradients, geometric sans.",
  palette: {
    slideBg: "#0a0b14",
    surface: "#181c39",
    accent: "#6366f1",
    onBg: "#e9ebff",
    onSurface: "#c9cdf2",
    onAccent: "#ffffff",
    muted: "#9aa2c8",
    deco: ["#22d3ee", "#a855f7", "#6366f1"],
  },
  fonts: {
    heading: "space-grotesk",
    body: "inter",
    headingCss: "'Space Grotesk', system-ui, sans-serif",
    bodyCss: "'Inter', system-ui, sans-serif",
  },
  cornerRadiusPt: 10,
  shadowCss: "0 18px 40px rgba(99,102,241,0.18)",
  defaultBackground: {
    type: "gradient",
    from: "#0a0b14",
    to: "#10132a",
    angle: 160,
  },
  masterBackground: {
    type: "gradient",
    from: "#0a0b14",
    to: "#10132a",
    angle: 160,
  },
  buildSlides: (s) => {
    const p = s.palette;
    const f = s.fonts;
    const glow = (
      z: number,
      box: Box,
      color: string,
      opacity = 0.55,
      options: { cx?: number; cy?: number; r?: number } = {},
    ) =>
      shape({
        zIndex: z,
        shape: "ellipse",
        box,
        fill: color,
        effect: { kind: "blur", radius: options.r ?? 8 },
        opacity,
        locked: true,
        name: "Glow",
      });
    return [
      // Cover
      slide(
        "aurora-cover",
        "Aurora",
        "title",
        [
          glow(1, { x: 58, y: -18, w: 60, h: 106 }, p.deco[1], 0.55, {
            r: 8,
          }),
          glow(2, { x: 60, y: 30, w: 46, h: 82 }, p.deco[0], 0.55, {
            r: 8,
          }),
          kicker(
            10,
            { x: 8, y: 9, w: 48, h: 6 },
            "PRODUCT KEYNOTE · 2026",
            p.deco[0],
            f.heading,
          ),
          text({
            zIndex: 11,
            box: { x: 8, y: 17, w: 44, h: 9.5 },
            role: "title",
            text: "Build the",
            style: {
              fontSize: 11,
              color: p.onBg,
              fontId: f.heading,
              bold: true,
              align: "left",
              lineHeight: 0.98,
            },
          }),
          text({
            zIndex: 11,
            box: { x: 8, y: 27.5, w: 18, h: 9.5 },
            role: "title",
            text: "next",
            style: {
              fontSize: 11,
              color: "#e9ebff",
              fontId: f.heading,
              bold: true,
              align: "left",
              lineHeight: 0.98,
            },
          }),
          text({
            zIndex: 11,
            box: { x: 24.2, y: 27.5, w: 27, h: 9.5 },
            role: "title",
            text: "frontier",
            style: {
              fontSize: 11,
              color: p.deco[0],
              fontId: f.heading,
              bold: true,
              align: "left",
              lineHeight: 0.98,
            },
          }),
          text({
            zIndex: 12,
            box: { x: 8, y: 40, w: 49, h: 9 },
            role: "subtitle",
            text: "A platform story told in light, motion, and momentum.",
            style: {
              fontSize: 3.4,
              color: p.muted,
              fontId: f.body,
              align: "left",
              lineHeight: 1.35,
            },
          }),
          glassPanel({
            zIndex: 12,
            box: { x: 8, y: 85, w: 13, h: 5.8 },
            fill: "#111827",
            radius: 50,
            intensity: "light",
            stroke: { color: "#ffffff", width: 0.14 },
            locked: true,
            name: "Studio chip",
          }),
          shape({
            zIndex: 13,
            shape: "circle",
            box: { x: 9.2, y: 87.2, w: 1.1, h: 1.9 },
            fill: p.deco[0],
            locked: true,
            name: "Chip dot",
          }),
          text({
            zIndex: 14,
            box: { x: 10.8, y: 85.7, w: 9.2, h: 4.5 },
            text: "Aurora Studio",
            style: {
              fontSize: 2.1,
              color: p.onBg,
              fontId: f.body,
              bold: true,
              align: "left",
              verticalAlign: "middle",
            },
          }),
        ],
        {
          type: "radialGradient",
          inner: "#1b1f4d",
          outer: "#07080f",
          cx: 80,
          cy: 0,
          r: 100,
        },
      ),
      // Section divider
      slide(
        "aurora-section",
        "01 — Vision",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: p.accent,
            opacity: 1,
            locked: true,
            name: "Field",
          }),
          glow(2, { x: -10, y: 45, w: 50, h: 70 }, p.deco[1]),
          glow(3, { x: 65, y: -20, w: 55, h: 70 }, p.deco[0]),
          text({
            zIndex: 10,
            box: { x: 9, y: 30, w: 20, h: 18 },
            text: "01",
            style: {
              fontSize: 14,
              color: "#ffffff",
              fontId: f.heading,
              bold: true,
              align: "left",
            },
            opacity: 0.5,
          }),
          text({
            zIndex: 11,
            box: { x: 9, y: 52, w: 70, h: 16 },
            role: "sectionTitle",
            text: "The vision behind the system",
            style: {
              fontSize: 6.4,
              color: "#ffffff",
              fontId: f.heading,
              bold: true,
              align: "left",
              lineHeight: 1.05,
            },
          }),
        ],
        { type: "solid", color: "#6366f1" },
      ),
      // Cards
      slide(
        "aurora-content",
        "Three forces",
        "content",
        [
          glow(1, { x: 62, y: -16, w: 42, h: 75 }, p.deco[1], 0.35, {
            r: 8,
          }),
          shape({
            zIndex: 3,
            shape: "rect",
            box: { x: 8, y: 14, w: 20, h: 1.2 },
            fill: linearFill(p.accent, p.deco[0], 90),
            radius: 50,
            locked: true,
            name: "Accent bar",
          }),
          text({
            zIndex: 10,
            box: { x: 8, y: 21, w: 58, h: 10 },
            role: "title",
            text: "Three forces converging",
            style: {
              fontSize: 6.4,
              color: p.onBg,
              fontId: f.heading,
              bold: true,
              align: "left",
              lineHeight: 1.02,
            },
          }),
          ...[
            {
              title: "Ambient compute",
              body: "cheap enough to disappear.",
              x: 8,
            },
            {
              title: "Adaptive tools",
              body: "fit the team, not the reverse.",
              x: 36,
            },
            {
              title: "Invisible UI",
              body: "the best interface vanishes.",
              x: 64,
            },
          ].flatMap((card, index) => [
            glassPanel({
              zIndex: 8,
              box: { x: card.x, y: 42, w: 24, h: 25 },
              fill: p.surface,
              radius: 14,
              intensity: "light",
              stroke: { color: "#ffffff", width: 0.14 },
              locked: true,
              name: `Card ${index + 1}`,
            }),
            text({
              zIndex: 10,
              box: { x: card.x + 2.2, y: 47, w: 19.5, h: 5.5 },
              role: "title",
              text: card.title,
              style: {
                fontSize: 3.4,
                color: p.onBg,
                fontId: f.heading,
                bold: true,
                align: "left",
              },
            }),
            text({
              zIndex: 10,
              box: { x: card.x + 2.2, y: 55, w: 19.5, h: 7 },
              role: "body",
              text: card.body,
              style: {
                fontSize: 2.4,
                color: p.muted,
                fontId: f.body,
                align: "left",
                lineHeight: 1.3,
              },
            }),
          ]),
        ],
        { type: "solid", color: p.slideBg },
      ),
      // Two-column
      slide("aurora-twocol", "Before / After", "two-column", [
        kicker(
          9,
          { x: 8, y: 12, w: 40, h: 5 },
          "BEFORE / AFTER",
          p.accent,
          f.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 8, y: 17, w: 80, h: 10 },
          role: "title",
          text: "From friction to flow",
          style: {
            fontSize: 5.6,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 8, y: 32, w: 40, h: 52 },
          fill: p.surface,
          radius: 14,
          locked: true,
          name: "Left card",
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 52, y: 32, w: 40, h: 52 },
          fill: "#ffffff",
          stroke: { color: p.accent, width: 0.5 },
          radius: 14,
          locked: true,
          name: "Right card",
        }),
        text({
          zIndex: 10,
          box: { x: 11, y: 36, w: 34, h: 6 },
          role: "label",
          text: "TODAY",
          style: {
            fontSize: 2.6,
            color: p.muted,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 10,
          box: { x: 11, y: 42, w: 34, h: 38 },
          role: "bullet",
          paragraphs: bullets([
            "Manual hand-offs",
            "Context lost between tools",
            "Slow feedback loops",
          ]),
          style: {
            fontSize: 3.1,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.4,
          },
        }),
        text({
          zIndex: 10,
          box: { x: 55, y: 36, w: 34, h: 6 },
          role: "label",
          text: "WITH AURORA",
          style: {
            fontSize: 2.6,
            color: p.accent,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 10,
          box: { x: 55, y: 42, w: 34, h: 38 },
          role: "bullet",
          paragraphs: bullets([
            "One continuous surface",
            "Shared, living context",
            "Answers in seconds",
          ]),
          style: {
            fontSize: 3.1,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.4,
          },
        }),
      ]),
      // Stat
      slide(
        "aurora-stat",
        "Impact",
        "title",
        [
          glow(1, { x: -12, y: 48, w: 50, h: 89 }, p.accent, 0.55, {
            r: 8,
          }),
          kicker(
            9,
            { x: 8, y: 9, w: 44, h: 6 },
            "MEASURED IMPACT",
            p.deco[0],
            f.heading,
          ),
          text({
            zIndex: 10,
            box: { x: 8, y: 17, w: 64, h: 31 },
            text: "4.8×",
            style: {
              fontSize: 26,
              color: p.deco[0],
              fontId: f.heading,
              bold: true,
              align: "left",
              lineHeight: 0.95,
            },
          }),
          text({
            zIndex: 11,
            box: { x: 8, y: 53, w: 56, h: 9 },
            role: "subtitle",
            text: "faster from idea to shipped across pilot teams.",
            style: {
              fontSize: 3,
              color: p.muted,
              fontId: f.body,
              align: "left",
              lineHeight: 1.35,
            },
          }),
        ],
        {
          type: "radialGradient",
          inner: "#14224d",
          outer: "#07080f",
          cx: 10,
          cy: 110,
          r: 100,
        },
      ),
      // Closing
      slide(
        "aurora-closing",
        "Thank you",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: p.onBg,
            locked: true,
            name: "Field",
          }),
          shape({
            zIndex: 2,
            shape: "ellipse",
            box: { x: 60, y: 30, w: 55, h: 75 },
            fill: p.accent,
            opacity: 0.4,
            locked: true,
            name: "Glow",
          }),
          text({
            zIndex: 10,
            box: { x: 9, y: 38, w: 60, h: 16 },
            role: "title",
            text: "Let's build it.",
            style: {
              fontSize: 8.5,
              color: "#ffffff",
              fontId: f.heading,
              bold: true,
              align: "left",
            },
          }),
          text({
            zIndex: 11,
            box: { x: 9.5, y: 58, w: 50, h: 8 },
            role: "subtitle",
            text: "hello@aurora.studio  ·  aurora.studio",
            style: {
              fontSize: 3.2,
              color: "#c7c9f5",
              fontId: f.body,
              align: "left",
            },
          }),
        ],
        { type: "solid", color: "#0b1020" },
      ),
    ];
  },
};

/* ======================================================================= *
 * 2. MONOLITH — corporate / consulting
 * ======================================================================= */

const monolith: ThemeSpec = {
  id: "monolith",
  name: "Monolith",
  tagline: "Corporate & consulting — navy, gold, crisp rules, zero radius.",
  palette: {
    slideBg: "#fbfbf9",
    surface: "#eef1f5",
    accent: "#b3892f",
    onBg: "#13243f",
    onSurface: "#27395a",
    onAccent: "#ffffff",
    muted: "#7a8aa3",
    deco: ["#13243f", "#b3892f", "#dfe4ea"],
  },
  fonts: {
    heading: "ibm-plex-sans",
    body: "ibm-plex-sans",
    headingCss: "'IBM Plex Sans', system-ui, sans-serif",
    bodyCss: "'IBM Plex Sans', system-ui, sans-serif",
  },
  cornerRadiusPt: 0,
  shadowCss: "none",
  defaultBackground: { type: "solid", color: "#fbfbf9" },
  masterBackground: { type: "solid", color: "#fbfbf9" },
  buildSlides: (s) => {
    const p = s.palette;
    const f = s.fonts;
    const rule = (z: number, box: Box, color = p.deco[2]) =>
      shape({
        zIndex: z,
        shape: "rect",
        box,
        fill: color,
        locked: true,
        name: "Rule",
      });
    return [
      // Cover
      slide("monolith-cover", "Monolith", "title", [
        shape({
          zIndex: 1,
          shape: "rect",
          box: { x: 0, y: 0, w: 34, h: 100 },
          fill: p.onBg,
          locked: true,
          name: "Sidebar",
        }),
        shape({
          zIndex: 2,
          shape: "rect",
          box: { x: 30.4, y: 0, w: 0.7, h: 100 },
          fill: p.accent,
          locked: true,
          name: "Spine",
        }),
        shape({
          zIndex: 3,
          shape: "rect",
          box: { x: 6, y: 16, w: 6, h: 6 },
          fill: p.accent,
          locked: true,
          name: "Mark",
        }),
        text({
          zIndex: 10,
          box: { x: 6, y: 70, w: 24, h: 16 },
          text: "MONOLITH\nPARTNERS",
          style: {
            fontSize: 2.6,
            color: "#ffffff",
            fontId: f.heading,
            bold: true,
            align: "left",
            lineHeight: 1.3,
          },
        }),
        kicker(
          10,
          { x: 40, y: 28, w: 50, h: 5 },
          "STRATEGY REVIEW · Q2 2026",
          p.accent,
          f.heading,
        ),
        rule(9, { x: 40, y: 35, w: 16, h: 0.5 }, p.accent),
        text({
          zIndex: 11,
          box: { x: 40, y: 38, w: 54, h: 24 },
          role: "title",
          text: "Operating model for the next decade",
          style: {
            fontSize: 6.6,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
            lineHeight: 1.08,
          },
        }),
        text({
          zIndex: 12,
          box: { x: 40, y: 66, w: 50, h: 8 },
          role: "subtitle",
          text: "Prepared for the Board of Directors",
          style: {
            fontSize: 3.1,
            color: p.muted,
            fontId: f.body,
            align: "left",
          },
        }),
      ]),
      // Section
      slide(
        "monolith-section",
        "Section",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: p.onBg,
            locked: true,
            name: "Field",
          }),
          shape({
            zIndex: 2,
            shape: "rect",
            box: { x: 8, y: 36, w: 10, h: 0.6 },
            fill: p.accent,
            locked: true,
            name: "Rule",
          }),
          text({
            zIndex: 10,
            box: { x: 8, y: 26, w: 30, h: 10 },
            text: "02",
            style: {
              fontSize: 6,
              color: p.accent,
              fontId: f.heading,
              bold: true,
              align: "left",
            },
          }),
          text({
            zIndex: 11,
            box: { x: 8, y: 40, w: 70, h: 18 },
            role: "sectionTitle",
            text: "Where value is created",
            style: {
              fontSize: 6.6,
              color: "#ffffff",
              fontId: f.heading,
              bold: true,
              align: "left",
              lineHeight: 1.05,
            },
          }),
          text({
            zIndex: 12,
            box: { x: 8, y: 60, w: 60, h: 8 },
            role: "subtitle",
            text: "Three levers, one integrated thesis.",
            style: {
              fontSize: 3.2,
              color: "#9fb0c9",
              fontId: f.body,
              align: "left",
            },
          }),
        ],
        { type: "solid", color: "#13243f" },
      ),
      // Content
      slide("monolith-content", "Findings", "content", [
        text({
          zIndex: 10,
          box: { x: 6, y: 10, w: 60, h: 8 },
          role: "title",
          text: "Key findings",
          style: {
            fontSize: 5.4,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        rule(9, { x: 6, y: 19, w: 88, h: 0.4 }),
        shape({
          zIndex: 9,
          shape: "rect",
          box: { x: 6, y: 23, w: 0.8, h: 56 },
          fill: p.accent,
          locked: true,
          name: "Tick",
        }),
        text({
          zIndex: 11,
          box: { x: 9, y: 24, w: 42, h: 56 },
          role: "bullet",
          paragraphs: bullets([
            "Margin compression concentrated in two business units.",
            "Shared services duplicate ~18% of back-office spend.",
            "Digital channel under-monetised versus peer set.",
            "Talent retention strong in core engineering.",
          ]),
          style: {
            fontSize: 3.1,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.55,
            paragraphSpacing: 1.8,
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 56, y: 24, w: 38, h: 55 },
          fill: p.surface,
          locked: true,
          name: "Panel",
        }),
        shape({
          zIndex: 9,
          shape: "rect",
          box: { x: 56, y: 24, w: 38, h: 1.2 },
          fill: p.accent,
          locked: true,
          name: "Panel top",
        }),
        text({
          zIndex: 10,
          box: { x: 59, y: 28, w: 32, h: 6 },
          role: "label",
          text: "BOTTOM LINE",
          style: {
            fontSize: 2.4,
            color: p.accent,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 59, y: 34, w: 32, h: 40 },
          role: "body",
          text: "A focused 18-month program can recover 320 bps of margin while funding the digital pivot.",
          style: {
            fontSize: 3.4,
            color: p.onBg,
            fontId: f.body,
            align: "left",
            lineHeight: 1.5,
          },
        }),
      ]),
      // Two-column
      slide("monolith-twocol", "Options", "two-column", [
        text({
          zIndex: 10,
          box: { x: 6, y: 10, w: 70, h: 8 },
          role: "title",
          text: "Two paths forward",
          style: {
            fontSize: 5.4,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        rule(9, { x: 6, y: 19, w: 88, h: 0.4 }),
        text({
          zIndex: 10,
          box: { x: 6, y: 24, w: 40, h: 6 },
          role: "label",
          text: "OPTION A — OPTIMISE",
          style: {
            fontSize: 2.6,
            color: p.accent,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 6, y: 30, w: 40, h: 48 },
          role: "bullet",
          paragraphs: bullets([
            "Lower execution risk",
            "Returns within 12 months",
            "Limited upside ceiling",
          ]),
          style: {
            fontSize: 3.1,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.6,
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 50, y: 22, w: 0.4, h: 58 },
          fill: p.deco[2],
          locked: true,
          name: "Divider",
        }),
        text({
          zIndex: 10,
          box: { x: 54, y: 24, w: 40, h: 6 },
          role: "label",
          text: "OPTION B — TRANSFORM",
          style: {
            fontSize: 2.6,
            color: p.accent,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 54, y: 30, w: 40, h: 48 },
          role: "bullet",
          paragraphs: bullets([
            "Higher execution risk",
            "Returns in 24–36 months",
            "Step-change in market position",
          ]),
          style: {
            fontSize: 3.1,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.6,
          },
        }),
      ]),
      // Stat
      slide(
        "monolith-stat",
        "Number",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: p.surface,
            locked: true,
            name: "Field",
          }),
          shape({
            zIndex: 2,
            shape: "rect",
            box: { x: 8, y: 30, w: 12, h: 0.6 },
            fill: p.accent,
            locked: true,
            name: "Rule",
          }),
          kicker(
            9,
            { x: 8, y: 23, w: 50, h: 5 },
            "TARGET OUTCOME",
            p.accent,
            f.heading,
          ),
          text({
            zIndex: 10,
            box: { x: 7.5, y: 33, w: 60, h: 26 },
            text: "320 bps",
            style: {
              fontSize: 15,
              color: p.onBg,
              fontId: f.heading,
              bold: true,
              align: "left",
            },
          }),
          text({
            zIndex: 11,
            box: { x: 8, y: 62, w: 60, h: 10 },
            role: "subtitle",
            text: "of operating-margin recovery within 18 months.",
            style: {
              fontSize: 3.6,
              color: p.onSurface,
              fontId: f.body,
              align: "left",
            },
          }),
        ],
        { type: "solid", color: "#eef1f5" },
      ),
      // Closing
      slide(
        "monolith-closing",
        "Discussion",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: p.onBg,
            locked: true,
            name: "Field",
          }),
          shape({
            zIndex: 2,
            shape: "rect",
            box: { x: 8, y: 44, w: 10, h: 0.6 },
            fill: p.accent,
            locked: true,
            name: "Rule",
          }),
          text({
            zIndex: 10,
            box: { x: 8, y: 36, w: 70, h: 10 },
            role: "title",
            text: "Discussion",
            style: {
              fontSize: 6.6,
              color: "#ffffff",
              fontId: f.heading,
              bold: true,
              align: "left",
            },
          }),
          text({
            zIndex: 11,
            box: { x: 8, y: 50, w: 60, h: 8 },
            role: "subtitle",
            text: "Monolith Partners  ·  strictly confidential",
            style: {
              fontSize: 3,
              color: "#9fb0c9",
              fontId: f.body,
              align: "left",
            },
          }),
        ],
        { type: "solid", color: "#13243f" },
      ),
    ];
  },
};

/* ======================================================================= *
 * 3. EDITORIAL — magazine / brand storytelling
 * ======================================================================= */

const editorial: ThemeSpec = {
  id: "editorial",
  name: "Editorial",
  tagline: "Magazine & brand storytelling — warm cream, serif display, coral.",
  palette: {
    slideBg: "#fbf6ee",
    surface: "#f1e7d8",
    accent: "#e0533b",
    onBg: "#211b17",
    onSurface: "#4b3f36",
    onAccent: "#ffffff",
    muted: "#8a7a6b",
    deco: ["#e0533b", "#211b17", "#caa26b"],
  },
  fonts: {
    heading: "source-serif-4",
    body: "source-sans-3",
    headingCss: "'Source Serif 4', Georgia, serif",
    bodyCss: "'Source Sans 3', system-ui, sans-serif",
  },
  cornerRadiusPt: 2,
  shadowCss: "none",
  defaultBackground: { type: "solid", color: "#fbf6ee" },
  masterBackground: { type: "solid", color: "#fbf6ee" },
  buildSlides: (s) => {
    const p = s.palette;
    const f = s.fonts;
    const underline = (z: number, box: Box) =>
      shape({
        zIndex: z,
        shape: "rect",
        box,
        fill: p.accent,
        locked: true,
        name: "Underline",
      });
    return [
      // Cover
      slide("editorial-cover", "Editorial", "title", [
        shape({
          zIndex: 1,
          shape: "rect",
          box: { x: 4, y: 5, w: 92, h: 90 },
          fill: p.slideBg,
          stroke: { color: p.onBg, width: 0.4 },
          locked: true,
          name: "Frame",
        }),
        kicker(
          9,
          { x: 9, y: 13, w: 50, h: 5 },
          "ISSUE Nº 04 — THE CRAFT EDITION",
          p.accent,
          f.body,
        ),
        text({
          zIndex: 10,
          box: { x: 8.5, y: 30, w: 80, h: 30 },
          role: "title",
          text: "Making things\nworth keeping",
          style: {
            fontSize: 11,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            italic: true,
            align: "left",
            lineHeight: 1.0,
          },
        }),
        underline(9, { x: 9, y: 60, w: 22, h: 0.9 }),
        text({
          zIndex: 11,
          box: { x: 9, y: 64, w: 60, h: 8 },
          role: "subtitle",
          text: "On patience, taste, and the long game of brand.",
          style: {
            fontSize: 3.4,
            color: p.muted,
            fontId: f.body,
            align: "left",
          },
        }),
      ]),
      // Section
      slide(
        "editorial-section",
        "Chapter",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: p.accent,
            locked: true,
            name: "Field",
          }),
          text({
            zIndex: 9,
            box: { x: 60, y: -6, w: 50, h: 60 },
            text: "“",
            style: {
              fontSize: 40,
              color: "#ffffff",
              fontId: f.heading,
              bold: true,
              align: "left",
            },
            opacity: 0.18,
          }),
          text({
            zIndex: 10,
            box: { x: 9, y: 26, w: 30, h: 10 },
            text: "Chapter Two",
            style: {
              fontSize: 3.4,
              color: "#ffe7df",
              fontId: f.body,
              bold: true,
              align: "left",
            },
          }),
          text({
            zIndex: 11,
            box: { x: 8.5, y: 34, w: 74, h: 30 },
            role: "sectionTitle",
            text: "The first ten\nseconds",
            style: {
              fontSize: 9,
              color: "#ffffff",
              fontId: f.heading,
              bold: true,
              italic: true,
              align: "left",
              lineHeight: 1.0,
            },
          }),
        ],
        { type: "solid", color: "#e0533b" },
      ),
      // Content (drop-cap editorial)
      slide("editorial-content", "Essay", "content", [
        kicker(9, { x: 8, y: 12, w: 40, h: 5 }, "FEATURE", p.accent, f.body),
        text({
          zIndex: 10,
          box: { x: 8, y: 17, w: 60, h: 12 },
          role: "title",
          text: "A house style is a promise",
          style: {
            fontSize: 5.6,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            italic: true,
            align: "left",
            lineHeight: 1.05,
          },
        }),
        underline(9, { x: 8, y: 30, w: 14, h: 0.8 }),
        text({
          zIndex: 11,
          box: { x: 8, y: 34, w: 40, h: 48 },
          role: "body",
          text: "Every typeface, margin, and colour is a small vow to the reader: this is who we are, and we will keep showing up the same way. Consistency is not the enemy of creativity — it is the stage on which creativity is finally legible.",
          style: {
            fontSize: 3.3,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.6,
            align: "left",
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 54, y: 22, w: 40, h: 60 },
          fill: p.surface,
          locked: true,
          name: "Plate",
        }),
        image({
          zIndex: 9,
          box: { x: 57, y: 25, w: 34, h: 48 },
          fitMode: "cover",
        }),
        text({
          zIndex: 10,
          box: { x: 57, y: 74, w: 34, h: 6 },
          role: "caption",
          text: "Fig. 1 — the grid, before the words arrive.",
          style: {
            fontSize: 2.2,
            color: p.muted,
            fontId: f.body,
            italic: true,
            align: "left",
          },
        }),
      ]),
      // Two-column
      slide("editorial-twocol", "Voice", "two-column", [
        text({
          zIndex: 10,
          box: { x: 8, y: 12, w: 80, h: 10 },
          role: "title",
          text: "How we sound",
          style: {
            fontSize: 5.6,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            italic: true,
            align: "left",
          },
        }),
        underline(9, { x: 8, y: 24, w: 14, h: 0.8 }),
        text({
          zIndex: 10,
          box: { x: 8, y: 30, w: 38, h: 6 },
          role: "label",
          text: "WE ARE",
          style: {
            fontSize: 2.6,
            color: p.accent,
            fontId: f.body,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 36, w: 38, h: 44 },
          role: "bullet",
          paragraphs: bullets([
            "Warm, never saccharine",
            "Confident, never loud",
            "Specific, never vague",
          ]),
          style: {
            fontSize: 3.2,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.6,
          },
        }),
        text({
          zIndex: 10,
          box: { x: 54, y: 30, w: 38, h: 6 },
          role: "label",
          text: "WE AVOID",
          style: {
            fontSize: 2.6,
            color: p.muted,
            fontId: f.body,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 54, y: 36, w: 38, h: 44 },
          role: "bullet",
          paragraphs: bullets([
            "Jargon and buzzwords",
            "Exclamation marks",
            "Promises we can't keep",
          ]),
          style: {
            fontSize: 3.2,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.6,
          },
        }),
      ]),
      // Pull-quote
      slide("editorial-stat", "Pull quote", "title", [
        text({
          zIndex: 9,
          box: { x: 6, y: 8, w: 30, h: 30 },
          text: "“",
          style: {
            fontSize: 30,
            color: p.accent,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 10,
          box: { x: 14, y: 30, w: 72, h: 34 },
          role: "quote",
          text: "Taste is just attention, paid consistently, until it looks effortless.",
          style: {
            fontSize: 6.2,
            color: p.onBg,
            fontId: f.heading,
            italic: true,
            align: "left",
            lineHeight: 1.2,
          },
        }),
        underline(9, { x: 14, y: 68, w: 10, h: 0.8 }),
        text({
          zIndex: 11,
          box: { x: 14, y: 71, w: 50, h: 6 },
          role: "caption",
          text: "— Editorial Director",
          style: { fontSize: 3, color: p.muted, fontId: f.body, align: "left" },
        }),
      ]),
      // Closing
      slide("editorial-closing", "Colophon", "title", [
        shape({
          zIndex: 1,
          shape: "rect",
          box: { x: 4, y: 5, w: 92, h: 90 },
          fill: p.slideBg,
          stroke: { color: p.onBg, width: 0.4 },
          locked: true,
          name: "Frame",
        }),
        text({
          zIndex: 10,
          box: { x: 9, y: 40, w: 70, h: 14 },
          role: "title",
          text: "Read on.",
          style: {
            fontSize: 9,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            italic: true,
            align: "left",
          },
        }),
        underline(9, { x: 9, y: 56, w: 16, h: 0.9 }),
        text({
          zIndex: 11,
          box: { x: 9, y: 60, w: 60, h: 8 },
          role: "subtitle",
          text: "Set in Source Serif 4 & Source Sans 3.  studio@editorial.press",
          style: { fontSize: 3, color: p.muted, fontId: f.body, align: "left" },
        }),
      ]),
    ];
  },
};

/* ======================================================================= *
 * 4. NOIR — dark premium pitch deck
 * ======================================================================= */

const noir: ThemeSpec = {
  id: "noir",
  name: "Noir",
  tagline: "Dark premium pitch deck — near-black canvas, amber accent, glow.",
  palette: {
    slideBg: "#0d0f14",
    surface: "#181b23",
    accent: "#f5b301",
    onBg: "#f2f3f5",
    onSurface: "#d4d7dd",
    onAccent: "#0d0f14",
    muted: "#8b909b",
    deco: ["#f5b301", "#38e1c2", "#262a35"],
  },
  fonts: {
    heading: "manrope",
    body: "inter",
    headingCss: "'Manrope', system-ui, sans-serif",
    bodyCss: "'Inter', system-ui, sans-serif",
  },
  cornerRadiusPt: 6,
  shadowCss: "0 20px 50px rgba(0,0,0,0.45)",
  defaultBackground: {
    type: "gradient",
    from: "#0d0f14",
    to: "#14171f",
    angle: 160,
  },
  masterBackground: {
    type: "gradient",
    from: "#0d0f14",
    to: "#14171f",
    angle: 160,
  },
  buildSlides: (s) => {
    const p = s.palette;
    const f = s.fonts;
    const dot = (z: number, x: number, color: string) =>
      shape({
        zIndex: z,
        shape: "ellipse",
        box: { x, y: 86, w: 1.4, h: 2.5 },
        fill: color,
        locked: true,
        name: "Dot",
      });
    return [
      // Cover
      slide("noir-cover", "Noir", "title", [
        shape({
          zIndex: 1,
          shape: "ellipse",
          box: { x: 55, y: -25, w: 70, h: 90 },
          fill: p.accent,
          opacity: 0.1,
          locked: true,
          name: "Glow",
        }),
        shape({
          zIndex: 2,
          shape: "rect",
          box: { x: 8, y: 33, w: 8, h: 0.5 },
          fill: p.accent,
          locked: true,
          name: "Rule",
        }),
        kicker(
          9,
          { x: 8, y: 26, w: 50, h: 5 },
          "SERIES A · CONFIDENTIAL",
          p.accent,
          f.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 7.5, y: 36, w: 78, h: 26 },
          role: "title",
          text: "The category\ndefining bet",
          style: {
            fontSize: 9.5,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
            lineHeight: 1.0,
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 66, w: 56, h: 8 },
          role: "subtitle",
          text: "Infrastructure for the autonomous enterprise.",
          style: {
            fontSize: 3.4,
            color: p.muted,
            fontId: f.body,
            align: "left",
          },
        }),
        dot(9, 8, p.accent),
        dot(9, 10.5, p.deco[1]),
        dot(9, 13, p.muted),
      ]),
      // Section
      slide("noir-section", "Problem", "title", [
        shape({
          zIndex: 1,
          shape: "ellipse",
          box: { x: -20, y: 30, w: 60, h: 80 },
          fill: p.deco[1],
          opacity: 0.08,
          locked: true,
          name: "Glow",
        }),
        text({
          zIndex: 9,
          box: { x: 8, y: 24, w: 30, h: 12 },
          text: "01",
          style: {
            fontSize: 7,
            color: p.accent,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        shape({
          zIndex: 9,
          shape: "rect",
          box: { x: 8, y: 39, w: 9, h: 0.5 },
          fill: p.accent,
          locked: true,
          name: "Rule",
        }),
        text({
          zIndex: 10,
          box: { x: 8, y: 43, w: 76, h: 18 },
          role: "sectionTitle",
          text: "The problem is expensive",
          style: {
            fontSize: 7,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
            lineHeight: 1.05,
          },
        }),
      ]),
      // Content
      slide("noir-content", "Solution", "content", [
        kicker(
          9,
          { x: 8, y: 12, w: 40, h: 5 },
          "SOLUTION",
          p.accent,
          f.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 8, y: 17, w: 54, h: 12 },
          role: "title",
          text: "One control plane",
          style: {
            fontSize: 5.6,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 32, w: 42, h: 48 },
          role: "bullet",
          paragraphs: bullets([
            "Unifies fragmented tooling into one API.",
            "Policy and audit built in from day zero.",
            "Deploys in the customer's own cloud.",
          ]),
          style: {
            fontSize: 3.3,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.55,
            paragraphSpacing: 1.8,
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 56, y: 24, w: 38, h: 56 },
          fill: p.surface,
          radius: 8,
          locked: true,
          name: "Card",
        }),
        shape({
          zIndex: 9,
          shape: "rect",
          box: { x: 56, y: 24, w: 38, h: 1 },
          fill: p.accent,
          locked: true,
          name: "Card edge",
        }),
        image({
          zIndex: 10,
          box: { x: 59, y: 29, w: 32, h: 46 },
          radius: 6,
          fitMode: "cover",
        }),
      ]),
      // Two-column
      slide("noir-twocol", "Traction", "two-column", [
        text({
          zIndex: 10,
          box: { x: 8, y: 12, w: 70, h: 8 },
          role: "title",
          text: "Traction & team",
          style: {
            fontSize: 5.6,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 8, y: 28, w: 40, h: 54 },
          fill: p.surface,
          radius: 8,
          locked: true,
          name: "Left card",
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 52, y: 28, w: 40, h: 54 },
          fill: p.surface,
          radius: 8,
          locked: true,
          name: "Right card",
        }),
        text({
          zIndex: 10,
          box: { x: 11, y: 32, w: 34, h: 6 },
          role: "label",
          text: "TRACTION",
          style: {
            fontSize: 2.6,
            color: p.accent,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 11, y: 38, w: 34, h: 40 },
          role: "bullet",
          paragraphs: bullets([
            "$2.4M ARR, 18% MoM",
            "11 enterprise logos",
            "Net revenue retention 141%",
          ]),
          style: {
            fontSize: 3.1,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.6,
          },
        }),
        text({
          zIndex: 10,
          box: { x: 55, y: 32, w: 34, h: 6 },
          role: "label",
          text: "TEAM",
          style: {
            fontSize: 2.6,
            color: p.deco[1],
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 55, y: 38, w: 34, h: 40 },
          role: "bullet",
          paragraphs: bullets([
            "Ex-platform leads, two unicorns",
            "Shipped to 40M+ users",
            "Together for six years",
          ]),
          style: {
            fontSize: 3.1,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.6,
          },
        }),
      ]),
      // Stat
      slide("noir-stat", "Ask", "title", [
        shape({
          zIndex: 1,
          shape: "ellipse",
          box: { x: 58, y: 20, w: 55, h: 75 },
          fill: p.accent,
          opacity: 0.1,
          locked: true,
          name: "Glow",
        }),
        kicker(9, { x: 8, y: 24, w: 40, h: 5 }, "THE ASK", p.accent, f.heading),
        text({
          zIndex: 10,
          box: { x: 7.5, y: 30, w: 60, h: 26 },
          text: "$12M",
          style: {
            fontSize: 18,
            color: p.accent,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 58, w: 64, h: 10 },
          role: "subtitle",
          text: "Series A to reach $20M ARR and category leadership.",
          style: {
            fontSize: 3.6,
            color: p.onSurface,
            fontId: f.body,
            align: "left",
          },
        }),
      ]),
      // Closing
      slide("noir-closing", "Thank you", "title", [
        shape({
          zIndex: 1,
          shape: "ellipse",
          box: { x: 30, y: 30, w: 70, h: 90 },
          fill: p.accent,
          opacity: 0.1,
          locked: true,
          name: "Glow",
        }),
        shape({
          zIndex: 2,
          shape: "rect",
          box: { x: 8, y: 42, w: 8, h: 0.5 },
          fill: p.accent,
          locked: true,
          name: "Rule",
        }),
        text({
          zIndex: 10,
          box: { x: 8, y: 45, w: 70, h: 12 },
          role: "title",
          text: "Let's talk.",
          style: {
            fontSize: 8.5,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 60, w: 60, h: 8 },
          role: "subtitle",
          text: "founders@noir.vc  ·  noir.vc/deck",
          style: {
            fontSize: 3.2,
            color: p.muted,
            fontId: f.body,
            align: "left",
          },
        }),
      ]),
    ];
  },
};

/* ======================================================================= *
 * 5. TERRA — sustainability / nature / research
 * ======================================================================= */

const terra: ThemeSpec = {
  id: "terra",
  name: "Terra",
  tagline: "Sustainability & research — sage canvas, forest ink, terracotta.",
  palette: {
    slideBg: "#f4f6f0",
    surface: "#e4ece0",
    accent: "#c2683f",
    onBg: "#1f2a22",
    onSurface: "#37463a",
    onAccent: "#ffffff",
    muted: "#6f7d6c",
    deco: ["#3f6b4a", "#c2683f", "#cdd9c4"],
  },
  fonts: {
    heading: "manrope",
    body: "source-sans-3",
    headingCss: "'Manrope', system-ui, sans-serif",
    bodyCss: "'Source Sans 3', system-ui, sans-serif",
  },
  cornerRadiusPt: 16,
  shadowCss: "0 14px 30px rgba(31,42,34,0.12)",
  defaultBackground: { type: "solid", color: "#f4f6f0" },
  masterBackground: { type: "solid", color: "#f4f6f0" },
  buildSlides: (s) => {
    const p = s.palette;
    const f = s.fonts;
    const leaf = (z: number, box: Box, color: string, rot: number, op = 0.5) =>
      shape({
        zIndex: z,
        shape: "ellipse",
        box,
        fill: color,
        opacity: op,
        rotation: rot,
        locked: true,
        name: "Leaf",
      });
    return [
      // Cover
      slide("terra-cover", "Terra", "title", [
        leaf(1, { x: 62, y: -20, w: 60, h: 70 }, p.deco[2], 12, 0.9),
        leaf(2, { x: 74, y: 14, w: 42, h: 52 }, p.deco[0], -8, 0.25),
        shape({
          zIndex: 3,
          shape: "ellipse",
          box: { x: 84, y: 56, w: 8, h: 14 },
          fill: p.accent,
          locked: true,
          name: "Seed",
        }),
        kicker(
          9,
          { x: 9, y: 28, w: 50, h: 5 },
          "IMPACT REPORT · 2026",
          p.accent,
          f.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 8.5, y: 34, w: 60, h: 24 },
          role: "title",
          text: "Growing what\nwe measure",
          style: {
            fontSize: 8.6,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
            lineHeight: 1.02,
          },
        }),
        text({
          zIndex: 11,
          box: { x: 9, y: 62, w: 52, h: 10 },
          role: "subtitle",
          text: "A year of regenerative progress, in the open.",
          style: {
            fontSize: 3.4,
            color: p.muted,
            fontId: f.body,
            align: "left",
          },
        }),
      ]),
      // Section
      slide(
        "terra-section",
        "Pillar",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: p.deco[0],
            locked: true,
            name: "Field",
          }),
          leaf(2, { x: -14, y: 40, w: 50, h: 64 }, "#ffffff", 0, 0.08),
          leaf(2, { x: 70, y: -16, w: 50, h: 60 }, p.accent, 0, 0.3),
          text({
            zIndex: 10,
            box: { x: 9, y: 28, w: 30, h: 8 },
            text: "Pillar 02",
            style: {
              fontSize: 3.2,
              color: "#cfe3cf",
              fontId: f.body,
              bold: true,
              align: "left",
            },
          }),
          text({
            zIndex: 11,
            box: { x: 8.5, y: 36, w: 74, h: 24 },
            role: "sectionTitle",
            text: "Soil, water,\nand carbon",
            style: {
              fontSize: 8,
              color: "#ffffff",
              fontId: f.heading,
              bold: true,
              align: "left",
              lineHeight: 1.02,
            },
          }),
        ],
        { type: "solid", color: "#3f6b4a" },
      ),
      // Content
      slide("terra-content", "Approach", "content", [
        kicker(
          9,
          { x: 8, y: 12, w: 40, h: 5 },
          "APPROACH",
          p.accent,
          f.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 8, y: 17, w: 54, h: 12 },
          role: "title",
          text: "Measure, restore, repeat",
          style: {
            fontSize: 5.4,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
            lineHeight: 1.05,
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 33, w: 42, h: 48 },
          role: "bullet",
          paragraphs: bullets([
            "Baseline every site with open sensor data.",
            "Restore with native species and no-till methods.",
            "Verify outcomes through third-party audit.",
          ]),
          style: {
            fontSize: 3.3,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.55,
            paragraphSpacing: 1.8,
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 56, y: 22, w: 38, h: 60 },
          fill: p.surface,
          radius: 22,
          locked: true,
          name: "Card",
        }),
        image({
          zIndex: 9,
          box: { x: 59, y: 26, w: 32, h: 44 },
          radius: 16,
          fitMode: "cover",
        }),
        text({
          zIndex: 10,
          box: { x: 59, y: 72, w: 32, h: 6 },
          role: "caption",
          text: "Restored wetland, North Basin.",
          style: {
            fontSize: 2.2,
            color: p.muted,
            fontId: f.body,
            align: "left",
          },
        }),
      ]),
      // Two-column
      slide("terra-twocol", "Targets", "two-column", [
        text({
          zIndex: 10,
          box: { x: 8, y: 12, w: 70, h: 8 },
          role: "title",
          text: "Where we stand",
          style: {
            fontSize: 5.4,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 8, y: 26, w: 40, h: 56 },
          fill: p.surface,
          radius: 20,
          locked: true,
          name: "Left card",
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 52, y: 26, w: 40, h: 56 },
          fill: p.deco[0],
          radius: 20,
          locked: true,
          name: "Right card",
        }),
        text({
          zIndex: 10,
          box: { x: 11, y: 30, w: 34, h: 6 },
          role: "label",
          text: "ACHIEVED",
          style: {
            fontSize: 2.6,
            color: p.accent,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 11, y: 36, w: 34, h: 42 },
          role: "bullet",
          paragraphs: bullets([
            "14,200 acres under management",
            "31% average soil-carbon gain",
            "100% renewable operations",
          ]),
          style: {
            fontSize: 3.1,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.6,
          },
        }),
        text({
          zIndex: 10,
          box: { x: 55, y: 30, w: 34, h: 6 },
          role: "label",
          text: "BY 2030",
          style: {
            fontSize: 2.6,
            color: "#ffd9a8",
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 55, y: 36, w: 34, h: 42 },
          role: "bullet",
          paragraphs: bullets([
            "50,000 acres restored",
            "Net-negative across scope 1–3",
            "Open data for every site",
          ]),
          style: {
            fontSize: 3.1,
            color: "#eef4ea",
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.6,
          },
        }),
      ]),
      // Stat
      slide("terra-stat", "Metric", "title", [
        leaf(1, { x: -10, y: 35, w: 44, h: 60 }, p.deco[2], 0, 0.9),
        leaf(1, { x: 64, y: 18, w: 46, h: 64 }, p.accent, 0, 0.14),
        kicker(
          9,
          { x: 9, y: 24, w: 50, h: 5 },
          "HEADLINE METRIC",
          p.accent,
          f.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 8.5, y: 30, w: 60, h: 26 },
          text: "118k t",
          style: {
            fontSize: 16,
            color: p.deco[0],
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 9, y: 60, w: 62, h: 10 },
          role: "subtitle",
          text: "of CO₂e removed and verified this year.",
          style: {
            fontSize: 3.6,
            color: p.onSurface,
            fontId: f.body,
            align: "left",
          },
        }),
      ]),
      // Closing
      slide(
        "terra-closing",
        "Join us",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: p.deco[0],
            locked: true,
            name: "Field",
          }),
          leaf(2, { x: 58, y: 28, w: 55, h: 72 }, p.accent, 0, 0.35),
          text({
            zIndex: 10,
            box: { x: 9, y: 40, w: 60, h: 14 },
            role: "title",
            text: "Grow with us.",
            style: {
              fontSize: 8,
              color: "#ffffff",
              fontId: f.heading,
              bold: true,
              align: "left",
            },
          }),
          text({
            zIndex: 11,
            box: { x: 9.5, y: 58, w: 56, h: 8 },
            role: "subtitle",
            text: "field@terra.earth  ·  terra.earth/report",
            style: {
              fontSize: 3.2,
              color: "#cfe3cf",
              fontId: f.body,
              align: "left",
            },
          }),
        ],
        { type: "solid", color: "#3f6b4a" },
      ),
    ];
  },
};

/* ======================================================================= *
 * 6. PULSE — bold startup / marketing
 * ======================================================================= */

const pulse: ThemeSpec = {
  id: "pulse",
  name: "Pulse",
  tagline: "Bold startup & marketing — high-contrast geometry, hot gradient.",
  palette: {
    slideBg: "#ffffff",
    surface: "#fff0f5",
    accent: "#ec2d6f",
    onBg: "#190a14",
    onSurface: "#3a1226",
    onAccent: "#ffffff",
    muted: "#9a6f84",
    deco: ["#ec2d6f", "#ff7a18", "#7b2ff7"],
  },
  fonts: {
    heading: "space-grotesk",
    body: "manrope",
    headingCss: "'Space Grotesk', system-ui, sans-serif",
    bodyCss: "'Manrope', system-ui, sans-serif",
  },
  cornerRadiusPt: 4,
  shadowCss: "0 16px 34px rgba(236,45,111,0.22)",
  defaultBackground: {
    type: "gradient",
    from: "#ffffff",
    to: "#fff4f8",
    angle: 135,
  },
  masterBackground: {
    type: "gradient",
    from: "#ffffff",
    to: "#fff4f8",
    angle: 135,
  },
  buildSlides: (s) => {
    const p = s.palette;
    const f = s.fonts;
    return [
      // Cover
      slide("pulse-cover", "Pulse", "title", [
        shape({
          zIndex: 1,
          shape: "triangle",
          box: { x: 60, y: -10, w: 55, h: 80 },
          fill: p.deco[1],
          opacity: 0.9,
          rotation: 12,
          locked: true,
          name: "Wedge",
        }),
        shape({
          zIndex: 2,
          shape: "ellipse",
          box: { x: 74, y: 50, w: 30, h: 52 },
          fill: p.accent,
          opacity: 0.9,
          locked: true,
          name: "Orb",
        }),
        shape({
          zIndex: 3,
          shape: "rect",
          box: { x: 8, y: 36, w: 14, h: 1.6 },
          fill: p.accent,
          locked: true,
          name: "Bar",
        }),
        kicker(
          9,
          { x: 8, y: 28, w: 50, h: 5 },
          "LAUNCH 2026",
          p.accent,
          f.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 7.5, y: 40, w: 64, h: 28 },
          role: "title",
          text: "Move at the\nspeed of want",
          style: {
            fontSize: 10,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
            lineHeight: 0.98,
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 72, w: 52, h: 8 },
          role: "subtitle",
          text: "The growth engine for ambitious brands.",
          style: {
            fontSize: 3.4,
            color: p.muted,
            fontId: f.body,
            align: "left",
          },
        }),
      ]),
      // Section
      slide(
        "pulse-section",
        "Big idea",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: p.accent,
            locked: true,
            name: "Field",
          }),
          shape({
            zIndex: 2,
            shape: "triangle",
            box: { x: -12, y: 40, w: 50, h: 70 },
            fill: p.deco[1],
            opacity: 0.85,
            rotation: -8,
            locked: true,
            name: "Wedge",
          }),
          shape({
            zIndex: 3,
            shape: "ellipse",
            box: { x: 72, y: 8, w: 34, h: 56 },
            fill: p.deco[2],
            opacity: 0.6,
            locked: true,
            name: "Orb",
          }),
          text({
            zIndex: 10,
            box: { x: 9, y: 26, w: 30, h: 8 },
            text: "THE BIG IDEA",
            style: {
              fontSize: 3,
              color: "#ffe0ec",
              fontId: f.heading,
              bold: true,
              align: "left",
            },
          }),
          text({
            zIndex: 11,
            box: { x: 8.5, y: 34, w: 78, h: 30 },
            role: "sectionTitle",
            text: "Attention is\nthe new oil",
            style: {
              fontSize: 9.5,
              color: "#ffffff",
              fontId: f.heading,
              bold: true,
              align: "left",
              lineHeight: 0.98,
            },
          }),
        ],
        { type: "solid", color: "#ec2d6f" },
      ),
      // Content
      slide("pulse-content", "Playbook", "content", [
        shape({
          zIndex: 1,
          shape: "ellipse",
          box: { x: 80, y: 70, w: 26, h: 42 },
          fill: p.deco[1],
          opacity: 0.18,
          locked: true,
          name: "Orb",
        }),
        kicker(
          9,
          { x: 8, y: 12, w: 40, h: 5 },
          "PLAYBOOK",
          p.accent,
          f.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 8, y: 17, w: 54, h: 12 },
          role: "title",
          text: "Three moves that compound",
          style: {
            fontSize: 5.4,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
            lineHeight: 1.05,
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 33, w: 44, h: 48 },
          role: "bullet",
          paragraphs: bullets([
            "Hook fast — earn the first three seconds.",
            "Loop value — make sharing the default.",
            "Compound trust — show receipts, every time.",
          ]),
          style: {
            fontSize: 3.3,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.55,
            paragraphSpacing: 1.8,
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 56, y: 24, w: 38, h: 54 },
          fill: p.surface,
          radius: 8,
          locked: true,
          name: "Card",
        }),
        shape({
          zIndex: 9,
          shape: "triangle",
          box: { x: 58, y: 26, w: 12, h: 18 },
          fill: p.accent,
          locked: true,
          name: "Tab",
        }),
        image({
          zIndex: 10,
          box: { x: 59, y: 33, w: 32, h: 40 },
          radius: 6,
          fitMode: "cover",
        }),
      ]),
      // Two-column
      slide("pulse-twocol", "Plans", "two-column", [
        text({
          zIndex: 10,
          box: { x: 8, y: 12, w: 70, h: 8 },
          role: "title",
          text: "Pick your speed",
          style: {
            fontSize: 5.4,
            color: p.onBg,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 8, y: 26, w: 40, h: 56 },
          fill: p.surface,
          radius: 8,
          locked: true,
          name: "Left card",
        }),
        shape({
          zIndex: 8,
          shape: "rect",
          box: { x: 52, y: 26, w: 40, h: 56 },
          fill: p.accent,
          radius: 8,
          locked: true,
          name: "Right card",
        }),
        shape({
          zIndex: 9,
          shape: "rect",
          box: { x: 52, y: 26, w: 40, h: 1.5 },
          fill: p.deco[1],
          locked: true,
          name: "Highlight",
        }),
        text({
          zIndex: 10,
          box: { x: 11, y: 30, w: 34, h: 6 },
          role: "label",
          text: "STARTER",
          style: {
            fontSize: 2.8,
            color: p.accent,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 11, y: 36, w: 34, h: 42 },
          role: "bullet",
          paragraphs: bullets([
            "Core analytics",
            "3 campaigns / month",
            "Email support",
          ]),
          style: {
            fontSize: 3.1,
            color: p.onSurface,
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.6,
          },
        }),
        text({
          zIndex: 10,
          box: { x: 55, y: 30, w: 34, h: 6 },
          role: "label",
          text: "SCALE — POPULAR",
          style: {
            fontSize: 2.8,
            color: "#ffffff",
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 55, y: 36, w: 34, h: 42 },
          role: "bullet",
          paragraphs: bullets([
            "Predictive analytics",
            "Unlimited campaigns",
            "Dedicated strategist",
          ]),
          style: {
            fontSize: 3.1,
            color: "#ffe0ec",
            fontId: f.body,
            lineHeight: 1.6,
            paragraphSpacing: 1.6,
          },
        }),
      ]),
      // Stat
      slide("pulse-stat", "Result", "title", [
        shape({
          zIndex: 1,
          shape: "triangle",
          box: { x: 58, y: 24, w: 48, h: 70 },
          fill: p.deco[1],
          opacity: 0.16,
          rotation: 10,
          locked: true,
          name: "Wedge",
        }),
        kicker(
          9,
          { x: 8, y: 24, w: 50, h: 5 },
          "AVERAGE RESULT",
          p.accent,
          f.heading,
        ),
        text({
          zIndex: 10,
          box: { x: 7.5, y: 30, w: 60, h: 26 },
          text: "+212%",
          style: {
            fontSize: 17,
            color: p.accent,
            fontId: f.heading,
            bold: true,
            align: "left",
          },
        }),
        text({
          zIndex: 11,
          box: { x: 8, y: 60, w: 64, h: 10 },
          role: "subtitle",
          text: "qualified pipeline in the first ninety days.",
          style: {
            fontSize: 3.6,
            color: p.onSurface,
            fontId: f.body,
            align: "left",
          },
        }),
      ]),
      // Closing
      slide(
        "pulse-closing",
        "Go",
        "title",
        [
          shape({
            zIndex: 1,
            shape: "rect",
            box: { x: 0, y: 0, w: 100, h: 100 },
            fill: p.onBg,
            locked: true,
            name: "Field",
          }),
          shape({
            zIndex: 2,
            shape: "triangle",
            box: { x: 55, y: 20, w: 55, h: 80 },
            fill: p.accent,
            opacity: 0.9,
            rotation: 8,
            locked: true,
            name: "Wedge",
          }),
          shape({
            zIndex: 3,
            shape: "ellipse",
            box: { x: 12, y: 60, w: 20, h: 34 },
            fill: p.deco[1],
            opacity: 0.9,
            locked: true,
            name: "Orb",
          }),
          text({
            zIndex: 10,
            box: { x: 9, y: 36, w: 60, h: 16 },
            role: "title",
            text: "Ready? Go.",
            style: {
              fontSize: 10,
              color: "#ffffff",
              fontId: f.heading,
              bold: true,
              align: "left",
            },
          }),
          text({
            zIndex: 11,
            box: { x: 9.5, y: 58, w: 50, h: 8 },
            role: "subtitle",
            text: "hello@pulse.co  ·  pulse.co",
            style: {
              fontSize: 3.2,
              color: "#ffb3cd",
              fontId: f.body,
              align: "left",
            },
          }),
        ],
        { type: "solid", color: "#190a14" },
      ),
    ];
  },
};

export const THEMES: ThemeSpec[] = [
  clarity,
  ocean,
  aurora,
  monolith,
  editorial,
  noir,
  terra,
  pulse,
];
