// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Select the database engine at runtime. SQLite is the zero-setup default for
// local dev/test; Postgres is used in production. Anything other than the exact
// string "postgres" falls back to SQLite.
//
// NOTE: this file is loaded by Prisma CLI tooling which may run outside the
// app's TS path aliases, so it cannot import from src/lib/db-provider.ts.
// The logic below intentionally mirrors that single source of truth.
const provider =
  process.env["DB_PROVIDER"] === "postgres" ? "postgres" : "sqlite";
const isSqlite = provider === "sqlite";

// Each provider has its own schema file. Development applies the selected
// schema directly with `prisma db push` while schemas are changing quickly.
const schema = isSqlite
  ? "prisma/schema.sqlite.prisma"
  : "prisma/schema.prisma";

// DATABASE_URL wins when set; SQLite falls back to a local file so a fresh clone
// works with no configuration.
const url =
  process.env["DATABASE_URL"] ??
  (isSqlite ? "file:./prisma/dev.db" : undefined);

export default defineConfig({
  schema,
  migrations: {
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url,
  },
});
