import {
  AI_DECK_INPUT_LIMIT,
  AI_INPUT_LIMIT,
  DECK_OUTPUT_TOKEN_LIMIT,
  GENERATED_DECK_SLIDE_LIMIT,
} from "@/lib/limits/ai";
import {
  BRAND_FONT_UPLOAD_LIMIT,
  BRAND_LOGO_UPLOAD_LIMIT,
  IMPORT_TEXT_UPLOAD_LIMIT,
  IMPORT_UPLOAD_LIMIT,
  SLIDE_ASSET_DIMENSION_LIMIT,
  SLIDE_ASSET_UPLOAD_LIMIT,
} from "@/lib/limits/assets";
import {
  DECK_JSON_LIMIT,
  ELEMENTS_PER_SLIDE_LIMIT,
  INLINE_IMAGE_LIMIT,
  INLINE_IMAGES_LIMIT,
  SLIDE_COUNT_LIMIT,
  TIMING_BUDGETS,
  VISUALS_PER_DOCUMENT_LIMIT,
} from "@/lib/limits/deck";
import {
  COMMENT_LIMITS,
  DOCUMENT_CONTENT_LIMIT,
  DOCUMENT_TITLE_LIMIT,
  LEXICAL_STATE_LIMIT,
  TAG_NAME_LIMIT,
  WORKSPACE_NAME_LIMIT,
} from "@/lib/limits/document";
import type { LimitDefinition } from "@/lib/limits/budgets";

export const LIMIT_INVENTORY: readonly LimitDefinition[] = [
  DOCUMENT_TITLE_LIMIT,
  DOCUMENT_CONTENT_LIMIT,
  LEXICAL_STATE_LIMIT,
  WORKSPACE_NAME_LIMIT,
  TAG_NAME_LIMIT,
  ...COMMENT_LIMITS,
  DECK_JSON_LIMIT,
  SLIDE_COUNT_LIMIT,
  ELEMENTS_PER_SLIDE_LIMIT,
  VISUALS_PER_DOCUMENT_LIMIT,
  INLINE_IMAGE_LIMIT,
  INLINE_IMAGES_LIMIT,
  IMPORT_UPLOAD_LIMIT,
  IMPORT_TEXT_UPLOAD_LIMIT,
  BRAND_FONT_UPLOAD_LIMIT,
  BRAND_LOGO_UPLOAD_LIMIT,
  SLIDE_ASSET_UPLOAD_LIMIT,
  SLIDE_ASSET_DIMENSION_LIMIT,
  AI_INPUT_LIMIT,
  AI_DECK_INPUT_LIMIT,
  GENERATED_DECK_SLIDE_LIMIT,
  DECK_OUTPUT_TOKEN_LIMIT,
  ...TIMING_BUDGETS,
];
