import { test } from "node:test";
import assert from "node:assert/strict";

import * as vnext from "@/lib/presentation-vnext";

test("presentation-vnext barrel exposes the stable runtime surface", () => {
  const expectedRuntimeExports = [
    "isValidId",
    "makeDiagnostic",
    "DiagnosticCollector",
    "resolveToken",
    "STYLE_REFS",
    "isStyleRef",
    "DECK_SCHEMA_VERSION_V7",
    "safeParseDeckV7",
    "validateThemePackage",
    "resolveNodeStyle",
    "resolveTheme",
    "SEMANTIC_TEMPLATE_KINDS",
    "isSemanticTemplateKind",
    "SemanticTemplateRegistry",
    "selectLayout",
    "isSlotValue",
    "repairSemanticDeckPlan",
    "compileSlide",
    "resetIdCounter",
    "slideSpecFromSlide",
    "emptySlideSpecFromLayout",
    "resolveDeckRenderTree",
    "buildExportSpec",
    "insertSlide",
    "insertBlankSlide",
    "duplicateSlide",
    "deleteSlide",
    "moveSlide",
    "applyTemplate",
    "updateSlideControls",
    "updateSlideAttributes",
    "updateSlideLocalStyle",
    "resetSlideLocalStyle",
    "updateSlideSourceMetadata",
    "setThemePackage",
    "insertNode",
    "pasteNodes",
    "updateNodeContent",
    "resetImageCrop",
    "updateNodeLayout",
    "updateNodeRotation",
    "updateNodeLayouts",
    "updateNodeAttributes",
    "updateNodeSourceMetadata",
    "moveNodesBy",
    "deleteNodes",
    "duplicateNodes",
    "updateNodeStyleBinding",
    "updateLocalStyle",
    "resetLocalStyleOverride",
    "detachDecoration",
    "groupNodes",
    "ungroupNodes",
    "reorderZIndex",
    "updateAssetMetadata",
    "alignmentGuidesForFrames",
    "snapFrameToStageGuides",
    "normalizeSelectionFrame",
    "selectNodesInFrame",
    "createDefaultTemplateRegistry",
    "BUILT_IN_TEMPLATES",
    "NEUTRAL_THEME_PACKAGE",
    "THEME_PACKAGE_REGISTRY",
    "resolveThemePackageIdV7",
    "getThemePackageV7",
    "listThemePackagesV7",
    "resolveThemePackageForDeck",
    "createBlankDeckV7",
    "openDeckFromJson",
    "looksLikeDeckV7",
    "buildVnextPptxSpec",
    "textContentToPptxRuns",
    "vnextShapeToName",
    "applyVnextTextOp",
    "applyVnextShapeOp",
    "applyVnextImageOp",
    "applyVnextConnectorOp",
    "applyVnextTableOp",
    "applyVnextPptxSpec",
    "exportDeckV7AsPPTX",
    "SUPPORTED_VISUAL_COLOR_CHANNELS",
    "DEFAULT_VISUAL_CHANNEL_COLORS",
    "isSupportedVisualColorChannel",
    "normalizeVisualChannelColors",
    "visualChannelColorWithDefaults",
  ] as const;

  for (const name of expectedRuntimeExports) {
    assert.ok(name in vnext, `${name} should be exported by the barrel`);
  }
  assert.equal(vnext.DECK_SCHEMA_VERSION_V7, 7);
  assert.equal(vnext.isSupportedVisualColorChannel("primary"), true);
  assert.deepEqual(
    vnext.visualChannelColorWithDefaults({ primary: "#111111" }).primary,
    "#111111",
  );
});
