"use client";

/**
 * InspectorShell — tab strip + panel router for the v7 inspector.
 *
 * Reads the available panels for the current selection type via
 * `availablePanels` from `inspector-panel-ui.ts` and renders a tab strip
 * above the active panel content.
 *
 * When the selection changes and the current panel is no longer available,
 * the shell resets to the default panel for the new context.
 */

import { useState, type JSX, type ReactNode } from "react";

import type {
  SlideChildNode,
  SlideNode,
  SemanticTemplateKind,
  NodeSourceMetadata,
  SlideControls,
  SlideProps,
} from "@/lib/presentation-vnext/schema";
import type { StylePatch } from "@/lib/presentation-vnext/style-schema";
import type { StyleBinding } from "@/lib/presentation-vnext/style-schema";
import type {
  PresentationDiagnostic,
  DiagnosticAction,
} from "@/lib/presentation-vnext/diagnostics";

import {
  availablePanels,
  defaultPanelForNode,
  type InspectorPanelId,
} from "@/lib/presentation-vnext/inspector-panel-ui";

import { Tabs } from "@/components/ui/tabs";
import { cx } from "@/components/ui/tokens";

import {
  SlideControlsPanel,
  SlideSettingsPanel,
  NodeGeometryPanel,
  NodeContentPanel,
  LocalStylePanel,
  NodeSourcePanel,
  StyleBindingPanel,
  LocalOverrideBadge,
  DiagnosticsPanel,
  LayersPanel,
} from "./index";

// ---------------------------------------------------------------------------
// Sub-panel wrappers
// ---------------------------------------------------------------------------

function PanelSection({
  children,
  className,
}: {
  children: ReactNode;
  className?: string;
}) {
  return (
    <div
      role="tabpanel"
      className={cx("min-h-0 flex-1 overflow-y-auto", className)}
    >
      {children}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Notes mini-panel (simple textarea)
// ---------------------------------------------------------------------------

function NotesPanel({
  notes,
  onUpdateNotes,
}: {
  notes: string | undefined;
  onUpdateNotes: (notes: string) => void;
}) {
  return (
    <PanelSection>
      <div className="p-3">
        <label className="flex flex-col gap-1.5">
          <span className="text-[10px] font-bold uppercase tracking-[0.06em] text-ds-text-muted">
            Speaker Notes
          </span>
          <textarea
            rows={6}
            value={notes ?? ""}
            onChange={(e) => onUpdateNotes(e.currentTarget.value)}
            placeholder="Add speaker notes…"
            className="w-full resize-none rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface p-2 text-xs text-ds-text-primary placeholder:text-ds-text-muted focus:border-ds-accent focus:outline-none focus:ring-2 focus:ring-ds-focus-ring/20"
          />
        </label>
      </div>
    </PanelSection>
  );
}

// ---------------------------------------------------------------------------
// Decoration panel
// ---------------------------------------------------------------------------

function DecorationPanel({ onDetach }: { onDetach: () => void }) {
  return (
    <PanelSection>
      <div className="flex flex-col gap-2 p-3">
        <h4 className="text-[10px] font-bold uppercase tracking-[0.06em] text-ds-text-muted">
          Theme Decoration
        </h4>
        <p className="text-xs text-ds-text-secondary">
          This element is generated by the theme package. Detach it to make
          independent edits.
        </p>
        <button
          type="button"
          onClick={onDetach}
          className="self-start rounded-[var(--ds-radius-sm,6px)] border border-ds-border-subtle bg-ds-surface px-3 py-1 text-xs font-medium text-ds-text-primary transition-colors hover:bg-ds-surface-raised"
        >
          Detach from theme
        </button>
      </div>
    </PanelSection>
  );
}

// ---------------------------------------------------------------------------
// Arrangement panel (stub — wraps NodeGeometryPanel)
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface InspectorShellProps {
  // Slide context
  activeSlide: SlideNode | undefined;
  selectedNode: SlideChildNode | undefined;
  selectedIds: string[];
  isDecorationSelected: boolean;
  diagnostics: PresentationDiagnostic[];

  // Slide-level handlers
  onUpdateControls: (patch: Partial<SlideControls>) => void;
  onUpdateProps: (patch: Partial<SlideProps>) => void;
  onUpdateSlideAttributes: (patch: { name?: string; notes?: string }) => void;
  onUpdateSlideLocalStyle: (patch: StylePatch) => void;
  onResetSlideLocalStyle: () => void;
  onUpdateSlideSource: (source: NodeSourceMetadata | undefined) => void;

  // Node-level handlers
  onUpdateSelectedLayout: (patch: Record<string, unknown>) => void;
  onUpdateSelectedAttributes: (patch: {
    locked?: boolean;
    hidden?: boolean;
  }) => void;
  onUpdateSelectedContent: (patch: Record<string, unknown>) => void;
  onUpdateSelectedLocalStyle: (patch: StylePatch) => void;
  onResetToTheme: () => void;
  onUpdateSelectedSource: (source: NodeSourceMetadata | undefined) => void;
  onChangeStyleBinding: (binding: StyleBinding) => void;

  // Layers
  onSelectLayer: (nodeId: string) => void;
  onUpdateLayer: (
    nodeId: string,
    patch: { locked?: boolean; hidden?: boolean },
  ) => void;

  // Decoration
  onDetachDecoration: () => void;

  // Diagnostics
  onDiagnosticAction: (
    action: DiagnosticAction,
    diagnostic: PresentationDiagnostic,
  ) => void;

  // Template
  TEMPLATE_OPTIONS: { kind: SemanticTemplateKind; label: string }[];
  activeTemplate: { layouts: { id: string }[] } | undefined;
  activeLayoutId: string | undefined;
  onReapplyTemplate: (kind: SemanticTemplateKind, layoutId?: string) => void;

  // Mode
  selectionMode: "normal" | "layers";
  onToggleSelectionMode: () => void;
}

export function InspectorShell({
  activeSlide,
  selectedNode,
  selectedIds,
  isDecorationSelected,
  diagnostics,
  onUpdateControls,
  onUpdateProps,
  onUpdateSlideAttributes,
  onUpdateSlideLocalStyle,
  onResetSlideLocalStyle,
  onUpdateSlideSource,
  onUpdateSelectedLayout,
  onUpdateSelectedAttributes,
  onUpdateSelectedContent,
  onUpdateSelectedLocalStyle,
  onResetToTheme,
  onUpdateSelectedSource,
  onChangeStyleBinding,
  onSelectLayer,
  onUpdateLayer,
  onDetachDecoration,
  onDiagnosticAction,
  TEMPLATE_OPTIONS,
  activeTemplate,
  activeLayoutId,
  onReapplyTemplate,
  selectionMode,
  onToggleSelectionMode,
}: InspectorShellProps): JSX.Element {
  const nodeForRouting = isDecorationSelected ? null : (selectedNode ?? null);
  const multiSelect = selectedIds.length > 1;
  const panels = availablePanels(nodeForRouting, {
    multiSelect,
    isDecoration: isDecorationSelected,
    hasDiagnostics: diagnostics.length > 0,
  });
  const defaultPanel = defaultPanelForNode(
    nodeForRouting,
    isDecorationSelected,
  );

  const [activePanel, setActivePanel] =
    useState<InspectorPanelId>(defaultPanel);

  // Derive the effective panel: fall back to the default when the current
  // selection no longer exposes the previously-active panel.
  const panelIds = panels.map((p) => p.id);
  const effectivePanel: InspectorPanelId = panelIds.includes(activePanel)
    ? activePanel
    : defaultPanel;

  const tabOptions = panels.map((p) => ({
    value: p.id as string,
    label: p.label,
  }));

  // Identity label above the tab strip
  let identityLabel = "Inspector";
  if (isDecorationSelected) {
    identityLabel = "Decoration";
  } else if (selectedNode) {
    identityLabel =
      selectedNode.type.charAt(0).toUpperCase() + selectedNode.type.slice(1);
    if (selectedNode.name) identityLabel = selectedNode.name;
  } else if (activeSlide) {
    identityLabel = activeSlide.name ?? "Slide";
  }

  return (
    <aside
      role="region"
      aria-label="Inspector"
      className="flex w-[320px] shrink-0 flex-col overflow-hidden border-l border-ds-border-subtle bg-ds-surface"
    >
      {/* Identity header */}
      <div className="flex items-center justify-between border-b border-ds-border-subtle px-3 py-2">
        <span className="truncate text-xs font-medium text-ds-text-primary">
          {identityLabel}
        </span>
        <button
          type="button"
          onClick={onToggleSelectionMode}
          className={cx(
            "rounded-[var(--ds-radius-sm,6px)] px-2 py-0.5 text-[11px] font-medium transition-colors",
            selectionMode === "layers"
              ? "bg-ds-accent-surface text-ds-accent-text"
              : "text-ds-text-muted hover:text-ds-text-secondary",
          )}
          aria-pressed={selectionMode === "layers"}
        >
          Layers
        </button>
      </div>

      {/* Tab strip */}
      {tabOptions.length > 1 && (
        <Tabs
          options={tabOptions as { value: string; label: string }[]}
          value={effectivePanel}
          onChange={(v) => setActivePanel(v as InspectorPanelId)}
          aria-label="Inspector panels"
          size="sm"
        />
      )}

      {/* Panel content */}
      <div className="min-h-0 flex-1 overflow-y-auto">
        {/* Slide panel */}
        {effectivePanel === "slide" && activeSlide && (
          <PanelSection>
            <section className="flex flex-col gap-1.5 px-3 py-2.5">
              <h4 className="text-[10px] font-bold uppercase tracking-[0.06em] text-ds-text-muted">
                Template
              </h4>
              <label className="flex flex-col gap-1 text-xs text-ds-text-secondary">
                Kind
                <select
                  value={activeSlide.template.kind}
                  onChange={(e) =>
                    onReapplyTemplate(
                      e.currentTarget.value as SemanticTemplateKind,
                    )
                  }
                  className="rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface px-2 py-1 text-xs text-ds-text-primary"
                >
                  {TEMPLATE_OPTIONS.map((t) => (
                    <option key={t.kind} value={t.kind}>
                      {t.label}
                    </option>
                  ))}
                </select>
              </label>
              {activeTemplate && (
                <label className="flex flex-col gap-1 text-xs text-ds-text-secondary">
                  Layout
                  <select
                    value={activeLayoutId ?? activeTemplate.layouts[0]?.id}
                    onChange={(e) =>
                      onReapplyTemplate(
                        activeSlide.template.kind,
                        e.currentTarget.value,
                      )
                    }
                    className="rounded-[var(--ds-radius-md,8px)] border border-ds-border-subtle bg-ds-surface px-2 py-1 text-xs text-ds-text-primary"
                  >
                    {activeTemplate.layouts.map((l) => (
                      <option key={l.id} value={l.id}>
                        {l.id}
                      </option>
                    ))}
                  </select>
                </label>
              )}
            </section>
            <SlideControlsPanel
              controls={activeSlide.controls}
              props={activeSlide.props}
              onUpdateControls={onUpdateControls}
              onUpdateProps={onUpdateProps}
            />
            <SlideSettingsPanel
              slide={activeSlide}
              onUpdateSlide={onUpdateSlideAttributes}
              onUpdateSource={onUpdateSlideSource}
              onUpdateLocalStyle={onUpdateSlideLocalStyle}
              onResetLocalStyle={onResetSlideLocalStyle}
            />
          </PanelSection>
        )}

        {/* Notes panel */}
        {effectivePanel === "notes" && (
          <NotesPanel
            notes={activeSlide?.notes}
            onUpdateNotes={(notes) => onUpdateSlideAttributes({ notes })}
          />
        )}

        {/* Text panel — content + style controls */}
        {(effectivePanel === "text" || effectivePanel === "shape") &&
          selectedNode &&
          !isDecorationSelected && (
            <PanelSection>
              <div className="px-3 py-2">
                <LocalOverrideBadge
                  localStyle={selectedNode.localStyle}
                  onResetToTheme={onResetToTheme}
                />
              </div>
              <NodeContentPanel
                node={selectedNode}
                onUpdateContent={onUpdateSelectedContent}
              />
              <LocalStylePanel
                node={selectedNode}
                onUpdateLocalStyle={onUpdateSelectedLocalStyle}
              />
            </PanelSection>
          )}

        {/* Image / visual / line / table content panel */}
        {(effectivePanel === "image" ||
          effectivePanel === "visual" ||
          effectivePanel === "line" ||
          effectivePanel === "table") &&
          selectedNode &&
          !isDecorationSelected && (
            <PanelSection>
              <div className="px-3 py-2">
                <LocalOverrideBadge
                  localStyle={selectedNode.localStyle}
                  onResetToTheme={onResetToTheme}
                />
              </div>
              <NodeContentPanel
                node={selectedNode}
                onUpdateContent={onUpdateSelectedContent}
              />
            </PanelSection>
          )}

        {/* Adjust panel (image opacity/crop stubs) */}
        {effectivePanel === "adjust" && selectedNode && (
          <PanelSection>
            <div className="p-3 text-xs text-ds-text-muted">
              Adjust controls coming soon.
            </div>
          </PanelSection>
        )}

        {/* Arrange panel */}
        {effectivePanel === "arrange" &&
          selectedNode &&
          !isDecorationSelected && (
            <PanelSection>
              <div className="px-3 py-2">
                <LocalOverrideBadge
                  localStyle={selectedNode.localStyle}
                  onResetToTheme={onResetToTheme}
                />
              </div>
              <NodeGeometryPanel
                node={selectedNode}
                onUpdateLayout={
                  onUpdateSelectedLayout as Parameters<
                    typeof NodeGeometryPanel
                  >[0]["onUpdateLayout"]
                }
                onUpdateAttributes={onUpdateSelectedAttributes}
              />
            </PanelSection>
          )}

        {/* Effects panel (stub) */}
        {effectivePanel === "effects" && (
          <PanelSection>
            <div className="p-3 text-xs text-ds-text-muted">
              Effects controls coming soon.
            </div>
          </PanelSection>
        )}

        {/* Source panel */}
        {effectivePanel === "source" &&
          selectedNode &&
          !isDecorationSelected && (
            <PanelSection>
              <NodeSourcePanel
                node={selectedNode}
                onUpdateSource={onUpdateSelectedSource}
              />
            </PanelSection>
          )}

        {/* Style panel */}
        {effectivePanel === "style" &&
          selectedNode &&
          !isDecorationSelected && (
            <PanelSection>
              <StyleBindingPanel
                role={selectedNode.role}
                binding={selectedNode.style}
                onChangeStyleBinding={onChangeStyleBinding}
              />
              <LocalStylePanel
                node={selectedNode}
                onUpdateLocalStyle={onUpdateSelectedLocalStyle}
              />
            </PanelSection>
          )}

        {/* Layers panel */}
        {effectivePanel === "layers" && activeSlide && (
          <PanelSection>
            <LayersPanel
              nodes={activeSlide.children}
              selectedIds={selectedIds}
              onSelectNode={onSelectLayer}
              onUpdateNode={onUpdateLayer}
            />
          </PanelSection>
        )}

        {/* Decoration panel */}
        {effectivePanel === "decoration" && isDecorationSelected && (
          <DecorationPanel onDetach={onDetachDecoration} />
        )}

        {/* Diagnostics panel */}
        {effectivePanel === "diagnostics" && (
          <PanelSection>
            <DiagnosticsPanel
              diagnostics={diagnostics}
              onAction={onDiagnosticAction}
              hideInfo={false}
            />
          </PanelSection>
        )}
      </div>
    </aside>
  );
}
