/**
 * Icon-component registry: resolves a catalog icon name (see
 * `src/lib/icons/catalog.ts`) to its bundled `lucide-react` component.
 *
 * This module is the React-aware consumer of the framework-free catalog. Icons
 * are imported explicitly (not via a `* as Icons` namespace) so the bundler can
 * tree-shake to only the icons we actually ship. Every entry here corresponds to
 * a `name` in `ICON_CATALOG`; keep the two in sync (`isKnownIcon` validates
 * names, this map renders them).
 *
 * lucide icons are presentational and contain no `"use client"` directive, so
 * this registry is safe to import from the directive-free `VisualRenderer` and
 * thus works in both server and client components.
 */
import {
  Activity,
  Anchor,
  ArrowLeftRight,
  ArrowRight,
  Award,
  BadgeCheck,
  Banknote,
  BarChart,
  Bell,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Briefcase,
  Bug,
  Building,
  Calculator,
  Calendar,
  Check,
  CircleCheck,
  CircleHelp,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Component,
  CornerDownRight,
  Cpu,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Eye,
  Factory,
  FileText,
  Filter,
  Flag,
  Flame,
  Folder,
  Gauge,
  Gift,
  GitBranch,
  Globe,
  Goal,
  GraduationCap,
  Hammer,
  Handshake,
  Heart,
  Hourglass,
  Inbox,
  Info,
  Key,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  LineChart,
  Link,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Merge,
  MessageSquare,
  Milestone,
  MoveRight,
  Network,
  Package,
  Percent,
  Phone,
  PieChart,
  Plane,
  Puzzle,
  Receipt,
  Recycle,
  RefreshCw,
  Repeat,
  Rocket,
  Route,
  Scale,
  Search,
  Send,
  Server,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Shuffle,
  Smartphone,
  Sparkles,
  Split,
  Sprout,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  Telescope,
  Terminal,
  ThumbsUp,
  TreePine,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  User,
  Users,
  Wallet,
  Warehouse,
  Webhook,
  Workflow,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

// A plain object (not `new Map(...)`) on purpose: one catalog name is "Map",
// and importing the lucide `Map` component shadows the global `Map`
// constructor inside this module.
const ICON_COMPONENTS: Record<string, LucideIcon> = {
  Activity,
  Anchor,
  ArrowLeftRight,
  ArrowRight,
  Award,
  BadgeCheck,
  Banknote,
  BarChart,
  Bell,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Briefcase,
  Bug,
  Building,
  Calculator,
  Calendar,
  Check,
  CircleCheck,
  CircleHelp,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Component,
  CornerDownRight,
  Cpu,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Eye,
  Factory,
  FileText,
  Filter,
  Flag,
  Flame,
  Folder,
  Gauge,
  Gift,
  GitBranch,
  Globe,
  Goal,
  GraduationCap,
  Hammer,
  Handshake,
  Heart,
  Hourglass,
  Inbox,
  Info,
  Key,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  LineChart,
  Link,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Merge,
  MessageSquare,
  Milestone,
  MoveRight,
  Network,
  Package,
  Percent,
  Phone,
  PieChart,
  Plane,
  Puzzle,
  Receipt,
  Recycle,
  RefreshCw,
  Repeat,
  Rocket,
  Route,
  Scale,
  Search,
  Send,
  Server,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Shuffle,
  Smartphone,
  Sparkles,
  Split,
  Sprout,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  Telescope,
  Terminal,
  ThumbsUp,
  TreePine,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  User,
  Users,
  Wallet,
  Warehouse,
  Webhook,
  Workflow,
  Wrench,
  X,
  Zap,
};

/**
 * Resolves a catalog icon name to its lucide component, or `undefined` when the
 * name is not in the registry (so callers can gracefully render no icon). The
 * `hasOwnProperty` guard avoids matching inherited object keys (e.g. "toString").
 */
export function resolveIconComponent(
  name: string | null | undefined,
): LucideIcon | undefined {
  if (name == null) return undefined;
  return Object.prototype.hasOwnProperty.call(ICON_COMPONENTS, name)
    ? ICON_COMPONENTS[name]
    : undefined;
}
