#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

export function buildLocalEnv({
  databaseUrl = "file:./prisma/dev.db",
  authSecret = randomBytes(32).toString("base64"),
  port = 4000,
} = {}) {
  return [
    "# Generated by npm run dev:setup. Safe to edit; do not commit .env.",
    'DB_PROVIDER="sqlite"',
    `DATABASE_URL="${databaseUrl}"`,
    `AUTH_SECRET="${authSecret}"`,
    `AUTH_URL="http://localhost:${port}"`,
    `NEXT_PUBLIC_APP_URL="http://localhost:${port}"`,
    "",
  ].join("\n");
}

export function ensureLocalEnv(repoRoot = process.cwd()) {
  const envPath = join(repoRoot, ".env");
  if (existsSync(envPath)) {
    return { created: false, path: envPath };
  }
  writeFileSync(envPath, buildLocalEnv(), { mode: 0o600 });
  return { created: true, path: envPath };
}

function run(command, args, env) {
  console.log(`\n$ ${[command, ...args].join(" ")}`);
  return spawnSync(command, args, {
    stdio: "inherit",
    env,
  });
}

export function setupCommands({ skipDb = false } = {}) {
  if (skipDb) return [];
  return [
    ["npm", ["run", "db:generate"]],
    ["npm", ["run", "db:push"]],
  ];
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const skipDb = process.argv.includes("--no-db");
  const envResult = ensureLocalEnv();
  console.log(
    envResult.created
      ? "Created .env with SQLite defaults and a redacted local AUTH_SECRET."
      : ".env already exists; leaving it unchanged.",
  );
  console.log("Repair hint: npm run dev:doctor checks the resulting setup.");

  const env = {
    ...process.env,
    DB_PROVIDER: process.env.DB_PROVIDER || "sqlite",
    DATABASE_URL: process.env.DATABASE_URL || "file:./prisma/dev.db",
  };
  for (const [command, args] of setupCommands({ skipDb })) {
    const result = run(command, args, env);
    if (result.status !== 0) {
      process.exit(result.status ?? 1);
    }
  }

  if (skipDb) {
    console.log(
      "Skipped database setup (--no-db). Smallest repair: npm run db:push.",
    );
  }
}
