#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

export function buildLocalEnv({
  databaseUrl = "file:./prisma/dev.db",
  authSecret = randomBytes(32).toString("base64"),
  port = 4000,
} = {}) {
  return [
    "# Generated by npm run dev:setup. Safe to edit; do not commit .env.",
    'DB_PROVIDER="sqlite"',
    `DATABASE_URL="${databaseUrl}"`,
    `AUTH_SECRET="${authSecret}"`,
    `AUTH_URL="http://localhost:${port}"`,
    `NEXT_PUBLIC_APP_URL="http://localhost:${port}"`,
    "",
  ].join("\n");
}

export function ensureLocalEnv(repoRoot = process.cwd()) {
  const envPath = join(repoRoot, ".env");
  if (existsSync(envPath)) {
    return { created: false, path: envPath };
  }
  writeFileSync(envPath, buildLocalEnv(), { mode: 0o600 });
  return { created: true, path: envPath };
}

function run(command, args, env) {
  console.log(`\n$ ${[command, ...args].join(" ")}`);
  return spawnSync(command, args, {
    stdio: "inherit",
    env,
  });
}

export function setupCommands({ skipDb = false } = {}) {
  if (skipDb) return [];
  return [
    ["npm", ["run", "db:generate"]],
    ["npm", ["run", "db:push"]],
  ];
}

export function runDevSetup({
  argv = process.argv,
  processEnv = process.env,
  ensureEnv = ensureLocalEnv,
  runCommand = run,
  stdout = console.log,
  exit = process.exit,
} = {}) {
  const skipDb = argv.includes("--no-db");
  const envResult = ensureEnv();
  stdout(
    envResult.created
      ? "Created .env with SQLite defaults and a redacted local AUTH_SECRET."
      : ".env already exists; leaving it unchanged.",
  );
  stdout("Repair hint: npm run dev:doctor checks the resulting setup.");

  const env = {
    ...processEnv,
    DB_PROVIDER: processEnv.DB_PROVIDER || "sqlite",
    DATABASE_URL: processEnv.DATABASE_URL || "file:./prisma/dev.db",
  };
  for (const [command, args] of setupCommands({ skipDb })) {
    const result = runCommand(command, args, env);
    if (result.status !== 0) {
      exit(result.status ?? 1);
      return;
    }
  }

  if (skipDb) {
    stdout(
      "Skipped database setup (--no-db). Smallest repair: npm run db:push.",
    );
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  runDevSetup();
}
