import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  BarChart3,
  Baseline,
  Bold,
  Code,
  Columns2,
  Combine,
  Filter,
  GitBranch,
  Grid2x2,
  Heading1,
  Heading2,
  Heading3,
  Highlighter,
  Italic,
  Lightbulb,
  Link as LinkIcon,
  List,
  ListChecks,
  ListOrdered,
  Milestone,
  Minus,
  Network,
  Quote,
  RefreshCw,
  Strikethrough,
  Triangle,
  Underline,
  Workflow,
  type LucideIcon,
} from "lucide-react";

export const TOOL_ICONS = {
  alignCenter: AlignCenter,
  alignJustify: AlignJustify,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  barChart: BarChart3,
  baseline: Baseline,
  bold: Bold,
  code: Code,
  columns: Columns2,
  combine: Combine,
  filter: Filter,
  gitBranch: GitBranch,
  grid: Grid2x2,
  heading1: Heading1,
  heading2: Heading2,
  heading3: Heading3,
  highlighter: Highlighter,
  italic: Italic,
  lightbulb: Lightbulb,
  link: LinkIcon,
  list: List,
  listChecks: ListChecks,
  listOrdered: ListOrdered,
  milestone: Milestone,
  minus: Minus,
  network: Network,
  quote: Quote,
  refresh: RefreshCw,
  strikethrough: Strikethrough,
  triangle: Triangle,
  underline: Underline,
  workflow: Workflow,
} as const satisfies Record<string, LucideIcon>;

export type ToolIconName = keyof typeof TOOL_ICONS;

export function resolveToolIcon(name: ToolIconName): LucideIcon {
  return TOOL_ICONS[name];
}
